using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace Secp256k1Net.SourceGenerator;

[Generator]
public class InteropGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get additional files that are JSON
        var jsonFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith("secp256k1-api.json", StringComparison.OrdinalIgnoreCase))
            .Select((file, ct) => file.GetText(ct)?.ToString())
            .Where(content => content != null);

        context.RegisterSourceOutput(jsonFiles, GenerateSource!);
    }

    private void GenerateSource(SourceProductionContext context, string jsonContent)
    {
        try
        {
            var api = JsonSerializer.Deserialize<Secp256k1Api>(jsonContent, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            if (api == null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("SECP001", "Invalid JSON", "Failed to parse secp256k1-api.json", "Secp256k1Generator", DiagnosticSeverity.Error, true),
                    Location.None));
                return;
            }

            // Generate all interop code in a single file
            var nativeSource = GenerateNative(api);
            context.AddSource("Secp256k1.Native.g.cs", SourceText.From(nativeSource, Encoding.UTF8));
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("SECP002", "Generation Error", $"Error generating interop: {ex.Message}", "Secp256k1Generator", DiagnosticSeverity.Error, true),
                Location.None));
        }
    }

    private void GenerateFunctionPointerTypeDelegate(StringBuilder sb, FunctionPointerType fpType)
    {
        sb.AppendLine();
        if (!string.IsNullOrEmpty(fpType.Description))
        {
            sb.AppendLine($"    /// <summary>{EscapeXml(fpType.Description)}</summary>");
        }
        sb.AppendLine("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");

        var returnType = MapCTypeToCSharp(fpType.ReturnType);
        var hasPointerParams = fpType.Parameters.Any(p => p.Type.Contains("*"));

        sb.Append($"    public {(hasPointerParams ? "unsafe " : "")}delegate {returnType} {fpType.Name}(");

        var paramStrings = fpType.Parameters.Select(p =>
        {
            var csType = MapCTypeToCSharp(p.Type, p.Name);
            return $"{csType} {SanitizeParamName(p.Name)}";
        });

        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");
    }

    private void GenerateFunctionDelegate(StringBuilder sb, FunctionDef func)
    {
        sb.AppendLine();
        if (!string.IsNullOrEmpty(func.Description))
        {
            sb.AppendLine($"    /// <summary>{EscapeXml(CleanDescription(func.Description))}</summary>");
        }

        foreach (var param in func.Parameters)
        {
            if (!string.IsNullOrEmpty(param.Description))
            {
                sb.AppendLine($"    /// <param name=\"{SanitizeParamName(param.Name)}\">{EscapeXml(CleanDescription(param.Description))}</param>");
            }
        }

        if (!string.IsNullOrEmpty(func.ReturnDescription))
        {
            sb.AppendLine($"    /// <returns>{EscapeXml(CleanDescription(func.ReturnDescription))}</returns>");
        }

        var returnType = MapCTypeToCSharp(func.ReturnType);
        var hasPointerParams = func.Parameters.Any(p => p.Type.Contains("*"));

        // Create delegate name from function name
        var delegateName = func.Name;

        sb.Append($"    public {(hasPointerParams ? "unsafe " : "")}delegate {returnType} {delegateName}(");

        var paramStrings = func.Parameters.Select(p =>
        {
            var csType = MapCTypeToCSharp(p.Type, p.Name);
            var paramName = SanitizeParamName(p.Name);
            return $"{csType} {paramName}";
        });

        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");
    }

    private string GenerateNative(Secp256k1Api api)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();

        // Collect all unique function pointer signatures and generate type aliases (inside namespace, after using System)
        var signatureToAlias = CollectFunctionPointerSignatures(api);

        sb.AppendLine("#if NET8_0_OR_GREATER");
        foreach (var kvp in signatureToAlias.OrderBy(x => x.Value))
        {
            // Use fully-qualified System.IntPtr in using aliases since they're processed before using System;
            var fullyQualifiedSignature = kvp.Key.Replace("IntPtr", "System.IntPtr");
            sb.AppendLine($"using unsafe {kvp.Value} = {fullyQualifiedSignature};");
        }
        sb.AppendLine("#endif");
        sb.AppendLine();

        sb.AppendLine("namespace Secp256k1Net");
        sb.AppendLine("{");

        // Generate function pointer type delegates that are used in public/internal APIs (available for all targets)
        var publicDelegateTypes = new HashSet<string> { "secp256k1_ecdh_hash_function" };
        foreach (var fpType in api.FunctionPointerTypes.Where(f => publicDelegateTypes.Contains(f.Name)))
        {
            GenerateFunctionPointerTypeDelegate(sb, fpType);
        }

        // Generate remaining function pointer type delegates (legacy only)
        sb.AppendLine("#if !NET8_0_OR_GREATER");

        foreach (var fpType in api.FunctionPointerTypes.Where(f => !publicDelegateTypes.Contains(f.Name)))
        {
            GenerateFunctionPointerTypeDelegate(sb, fpType);
        }

        // Generate function delegates
        foreach (var func in api.Functions)
        {
            GenerateFunctionDelegate(sb, func);
        }

        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("    public unsafe partial class Secp256k1");
        sb.AppendLine("    {");

        // Generate symbol name constants
        sb.AppendLine("        // Native function symbol names");
        foreach (var func in api.Functions)
        {
            var symbolName = GetSymbolConstName(func.Name);
            sb.AppendLine($"        private const string {symbolName} = \"{func.Name}\";");
        }
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var symbolName = GetSymbolConstName(global.Name);
            sb.AppendLine($"        private const string {symbolName} = \"{global.Name}\";");
        }
        sb.AppendLine();

        // Modern .NET 8+ section with function pointers
        sb.AppendLine("#if NET8_0_OR_GREATER");
        GenerateModernFunctionPointers(sb, api, signatureToAlias);
        sb.AppendLine("#else");
        GenerateLegacyDelegates(sb, api);
        sb.AppendLine("#endif");

        // Generate LoadFunctions method
        sb.AppendLine();
        sb.AppendLine("        private static void LoadFunctions(IntPtr lib)");
        sb.AppendLine("        {");
        sb.AppendLine("#if NET8_0_OR_GREATER");
        GenerateModernLoadFunctions(sb, api, signatureToAlias);
        sb.AppendLine("#else");
        GenerateLegacyLoadFunctions(sb, api);
        sb.AppendLine("#endif");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private Dictionary<string, string> CollectFunctionPointerSignatures(Secp256k1Api api)
    {
        var signatureToAlias = new Dictionary<string, string>();
        var aliasCounter = 0;

        // Collect signatures from all functions
        foreach (var func in api.Functions)
        {
            var signature = GetModernFunctionPointerType(func);
            if (!signatureToAlias.ContainsKey(signature))
            {
                signatureToAlias[signature] = $"FnPtr{aliasCounter++}";
            }
        }

        // Collect signatures from global function pointers
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var signature = GetModernFunctionPointerTypeForGlobal(global, api);
            if (!signatureToAlias.ContainsKey(signature))
            {
                signatureToAlias[signature] = $"FnPtr{aliasCounter++}";
            }
        }

        return signatureToAlias;
    }

    private void GenerateModernFunctionPointers(StringBuilder sb, Secp256k1Api api, Dictionary<string, string> signatureToAlias)
    {
        sb.AppendLine("        // Function pointer declarations (modern .NET 8+)");

        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var funcPtrType = GetModernFunctionPointerType(func);
            var alias = signatureToAlias[funcPtrType];
            sb.AppendLine($"        private static {alias} {fieldName};");
        }

        // Global function pointer variables
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var funcPtrType = GetModernFunctionPointerTypeForGlobal(global, api);
            var alias = signatureToAlias[funcPtrType];
            sb.AppendLine($"        private static {alias} {fieldName};");
        }
    }

    private void GenerateLegacyDelegates(StringBuilder sb, Secp256k1Api api)
    {
        sb.AppendLine("        // Delegate instance fields (legacy .NET)");

        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var delegateType = func.Name;
            sb.AppendLine($"        private static {delegateType} {fieldName};");
        }

        // Global function pointer variables use their typedef type
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            sb.AppendLine($"        private static {global.Type} {fieldName};");
        }
    }

    private void GenerateModernLoadFunctions(StringBuilder sb, Secp256k1Api api, Dictionary<string, string> signatureToAlias)
    {
        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var symbolName = GetSymbolConstName(func.Name);
            var funcPtrType = GetModernFunctionPointerType(func);
            var alias = signatureToAlias[funcPtrType];

            sb.AppendLine($"            {fieldName} = ({alias})NativeLibrary.GetExport(lib, {symbolName});");
        }

        // Global function pointers are data symbols - need to read the pointer
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var symbolName = GetSymbolConstName(global.Name);
            var funcPtrType = GetModernFunctionPointerTypeForGlobal(global, api);
            var alias = signatureToAlias[funcPtrType];

            sb.AppendLine();
            sb.AppendLine($"            // {global.Name} is a data symbol (function pointer), not a function");
            sb.AppendLine($"            var {fieldName}Ptr = NativeLibrary.GetExport(lib, {symbolName});");
            sb.AppendLine($"            {fieldName} = ({alias})Marshal.ReadIntPtr({fieldName}Ptr);");
        }
    }

    private void GenerateLegacyLoadFunctions(StringBuilder sb, Secp256k1Api api)
    {
        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var symbolName = GetSymbolConstName(func.Name);
            var delegateType = func.Name;

            sb.AppendLine($"            {fieldName} = LoadLibNative.GetDelegate<{delegateType}>(lib, {symbolName});");
        }

        // Global function pointers are data symbols
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var symbolName = GetSymbolConstName(global.Name);

            sb.AppendLine();
            sb.AppendLine($"            // {global.Name} is a data symbol (function pointer), not a function");
            sb.AppendLine($"            {fieldName} = LoadLibNative.GetDelegate<{global.Type}>(lib, {symbolName}, Marshal.ReadIntPtr);");
        }
    }

    private string GetModernFunctionPointerType(FunctionDef func)
    {
        var returnType = MapCTypeToCSharpForFunctionPointer(func.ReturnType);

        var paramTypes = func.Parameters.Select(p => MapCTypeToCSharpForFunctionPointer(p.Type, p.Name)).ToList();

        if (paramTypes.Count == 0)
        {
            return $"delegate* unmanaged[Cdecl]<{returnType}>";
        }

        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", paramTypes)}, {returnType}>";
    }

    private string GetModernFunctionPointerTypeForGlobal(GlobalPointer global, Secp256k1Api api)
    {
        // Find the function pointer type definition
        var fpType = api.FunctionPointerTypes.FirstOrDefault(f => f.Name == global.Type);
        if (fpType == null)
        {
            // Fallback - return a generic function pointer
            return "delegate* unmanaged[Cdecl]<int>";
        }

        var returnType = MapCTypeToCSharpForFunctionPointer(fpType.ReturnType);
        var paramTypes = fpType.Parameters.Select(p => MapCTypeToCSharpForFunctionPointer(p.Type, p.Name)).ToList();

        if (paramTypes.Count == 0)
        {
            return $"delegate* unmanaged[Cdecl]<{returnType}>";
        }

        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", paramTypes)}, {returnType}>";
    }

    private string MapCTypeToCSharp(string cType, string? paramName = null)
    {
        cType = cType.Trim();

        // Handle inline function pointer types like "void (*)(const char*, void*)"
        if (cType.Contains("(*)"))
            return "IntPtr";

        // Handle specific secp256k1 types
        // Note: check for "secp256k1_context" with Contains() to handle "const secp256k1_context*"
        if (cType.Contains("secp256k1_context") && cType.Contains("*"))
            return "IntPtr";
        if (cType == "secp256k1_context")
            return "IntPtr";

        // Function pointer types as parameters
        if (cType.Contains("secp256k1_") && cType.Contains("function"))
            return "IntPtr";

        // Handle pointer types
        // Double pointers (** or "* const*" pattern) become IntPtr
        if (cType.EndsWith("**") || cType.Contains("* const*") || cType.Contains("**"))
            return "IntPtr";

        if (cType.Contains("*"))
        {

            // Most pointer types become void*
            if (cType.Contains("unsigned char") || cType.Contains("char"))
                return "void*";
            if (cType.Contains("secp256k1_"))
                return "void*";
            if (cType.Contains("void"))
                return "void*";
            if (cType.Contains("size_t"))
                return "nuint*";
            if (cType.Contains("int") && !cType.Contains("uint"))
                return "int*";

            return "void*";
        }

        // Non-pointer types
        return cType switch
        {
            "unsigned int" => "uint",
            "int" => "int",
            "size_t" => "nuint",
            "uint64_t" => "ulong",
            "int64_t" => "long",
            "uint32_t" => "uint",
            "int32_t" => "int",
            "void" => "void",
            _ => cType
        };
    }

    private string MapCTypeToCSharpForFunctionPointer(string cType, string? paramName = null)
    {
        cType = cType.Trim();

        // Handle inline function pointer types like "void (*)(const char*, void*)"
        if (cType.Contains("(*)"))
            return "IntPtr";

        // Handle specific secp256k1 types
        // Note: check for "secp256k1_context" with Contains() to handle "const secp256k1_context*"
        if (cType.Contains("secp256k1_context") && cType.Contains("*"))
            return "IntPtr";
        if (cType == "secp256k1_context")
            return "IntPtr";

        // Function pointer types as parameters
        if (cType.Contains("secp256k1_") && cType.Contains("function"))
            return "IntPtr";

        // Handle pointer types
        // Double pointers (** or "* const*" pattern) become IntPtr
        if (cType.EndsWith("**") || cType.Contains("* const*") || cType.Contains("**"))
            return "IntPtr";

        if (cType.Contains("*"))
        {

            if (cType.Contains("unsigned char") || cType.Contains("char"))
                return "void*";
            if (cType.Contains("secp256k1_"))
                return "void*";
            if (cType.Contains("void"))
                return "void*";
            if (cType.Contains("size_t"))
                return "nuint*";
            if (cType.Contains("int") && !cType.Contains("uint"))
                return "int*";

            return "void*";
        }

        // Non-pointer types
        return cType switch
        {
            "unsigned int" => "uint",
            "int" => "int",
            "size_t" => "nuint",
            "uint64_t" => "ulong",
            "int64_t" => "long",
            "uint32_t" => "uint",
            "int32_t" => "int",
            "void" => "void",
            _ => cType
        };
    }

    private static string GetFieldName(string functionName)
    {
        // secp256k1_context_create -> _context_create
        if (functionName.StartsWith("secp256k1_"))
        {
            return "_" + functionName.Substring("secp256k1_".Length);
        }
        return "_" + functionName;
    }

    private static string GetSymbolConstName(string functionName)
    {
        // secp256k1_context_create -> SYM_context_create
        if (functionName.StartsWith("secp256k1_"))
        {
            return "SYM_" + functionName.Substring("secp256k1_".Length);
        }
        return "SYM_" + functionName;
    }

    private static string SanitizeParamName(string name)
    {
        // Handle C# reserved words
        return name switch
        {
            "data" => "data",
            "output" => "output",
            "input" => "input",
            "in" => "@in",
            "out" => "@out",
            "ref" => "@ref",
            _ => name
        };
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");
    }

    private static string CleanDescription(string? text)
    {
        if (string.IsNullOrEmpty(text))
            return "";

        // Remove newlines
        return text.Replace("\n", " ").Replace("\r", "");
    }

    // JSON model classes
    private class Secp256k1Api
    {
        public string Version { get; set; } = "";
        public string GeneratedAt { get; set; } = "";
        public List<string> Headers { get; set; } = new();
        public List<StructDef> Structs { get; set; } = new();
        public List<FunctionPointerType> FunctionPointerTypes { get; set; } = new();
        public List<FunctionDef> Functions { get; set; } = new();
        public List<ConstantDef> Constants { get; set; } = new();
        public List<GlobalPointer> GlobalPointers { get; set; } = new();
    }

    private class StructDef
    {
        public string Name { get; set; } = "";
        public int Size { get; set; }
        public string? Description { get; set; }
    }

    private class FunctionPointerType
    {
        public string Name { get; set; } = "";
        public string ReturnType { get; set; } = "";
        public List<ParameterDef> Parameters { get; set; } = new();
        public string? Description { get; set; }
    }

    private class FunctionDef
    {
        public string Name { get; set; } = "";
        public string ReturnType { get; set; } = "";
        public bool WarnUnusedResult { get; set; }
        public List<ParameterDef> Parameters { get; set; } = new();
        public string? Description { get; set; }
        public string? ReturnDescription { get; set; }
        public string? SourceHeader { get; set; }
    }

    private class ParameterDef
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
        public string? Direction { get; set; }
        public bool Nonnull { get; set; }
        public string? Description { get; set; }
    }

    private class ConstantDef
    {
        public string Name { get; set; } = "";
        public string Value { get; set; } = "";
        public long? NumericValue { get; set; }
        public string? Description { get; set; }
    }

    private class GlobalPointer
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
        public bool IsConst { get; set; }
        public string? Description { get; set; }
    }
}
