using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace Secp256k1Net.SourceGenerator;

[Generator]
public class InteropGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get additional files that are JSON
        var jsonFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith("secp256k1-api.json", StringComparison.OrdinalIgnoreCase))
            .Select((file, ct) => file.GetText(ct)?.ToString())
            .Where(content => content != null);

        context.RegisterSourceOutput(jsonFiles, GenerateSource!);
    }

    private void GenerateSource(SourceProductionContext context, string jsonContent)
    {
        try
        {
            var api = JsonSerializer.Deserialize<Secp256k1Api>(jsonContent, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            if (api == null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("SECP001", "Invalid JSON", "Failed to parse secp256k1-api.json", "Secp256k1Generator", DiagnosticSeverity.Error, true),
                    Location.None));
                return;
            }

            // Generate all interop code in a single file
            var nativeSource = GenerateNative(api);
            context.AddSource("Secp256k1.Native.g.cs", SourceText.From(nativeSource, Encoding.UTF8));

            // Generate safe wrapper methods
            var wrappersSource = GenerateWrappers(api);
            context.AddSource("Secp256k1.Wrappers.g.cs", SourceText.From(wrappersSource, Encoding.UTF8));
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("SECP002", "Generation Error", $"Error generating interop: {ex.Message}", "Secp256k1Generator", DiagnosticSeverity.Error, true),
                Location.None));
        }
    }

    private void GenerateFunctionPointerTypeDelegate(StringBuilder sb, FunctionPointerType fpType)
    {
        sb.AppendLine();
        if (!string.IsNullOrEmpty(fpType.Description))
        {
            sb.AppendLine($"    /// <summary>{FormatXmlDescription(fpType.Description)}</summary>");
        }
        sb.AppendLine("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");

        var returnType = MapCTypeToCSharp(fpType.ReturnType);
        var hasPointerParams = fpType.Parameters.Any(p => p.Type.Contains("*"));

        sb.Append($"    public {(hasPointerParams ? "unsafe " : "")}delegate {returnType} {fpType.Name}(");

        var paramStrings = fpType.Parameters.Select(p =>
        {
            var csType = MapCTypeToCSharp(p.Type, p.Name);
            return $"{csType} {SanitizeParamName(p.Name)}";
        });

        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");
    }

    private void GenerateFunctionDelegate(StringBuilder sb, FunctionDef func)
    {
        sb.AppendLine();
        if (!string.IsNullOrEmpty(func.Description))
        {
            sb.AppendLine($"    /// <summary>{FormatXmlDescription(func.Description)}</summary>");
        }

        foreach (var param in func.Parameters)
        {
            // Always generate param tags to avoid CS1573 warnings
            var description = FormatXmlDescription(param.Description);
            sb.AppendLine($"    /// <param name=\"{param.Name}\">{description}</param>");
        }

        if (!string.IsNullOrEmpty(func.ReturnDescription))
        {
            sb.AppendLine($"    /// <returns>{FormatXmlDescription(func.ReturnDescription)}</returns>");
        }

        var returnType = MapCTypeToCSharp(func.ReturnType);
        var hasPointerParams = func.Parameters.Any(p => p.Type.Contains("*"));

        // Create delegate name from function name
        var delegateName = func.Name;

        sb.Append($"    public {(hasPointerParams ? "unsafe " : "")}delegate {returnType} {delegateName}(");

        var paramStrings = func.Parameters.Select(p =>
        {
            var csType = MapCTypeToCSharp(p.Type, p.Name);
            var paramName = SanitizeParamName(p.Name);
            return $"{csType} {paramName}";
        });

        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");
    }

    private string GenerateNative(Secp256k1Api api)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();

        // Collect all unique function pointer signatures and generate type aliases (inside namespace, after using System)
        var signatureToAlias = CollectFunctionPointerSignatures(api);

        sb.AppendLine("#if NET8_0_OR_GREATER");
        foreach (var kvp in signatureToAlias.OrderBy(x => x.Value))
        {
            // Use fully-qualified System.IntPtr in using aliases since they're processed before using System;
            var fullyQualifiedSignature = kvp.Key.Replace("IntPtr", "System.IntPtr");
            sb.AppendLine($"using unsafe {kvp.Value} = {fullyQualifiedSignature};");
        }
        sb.AppendLine("#endif");
        sb.AppendLine();

        sb.AppendLine("namespace Secp256k1Net");
        sb.AppendLine("{");

        // Generate function pointer type delegates that are used in public/internal APIs (available for all targets)
        var publicDelegateTypes = new HashSet<string> { "secp256k1_ecdh_hash_function" };
        foreach (var fpType in api.FunctionPointerTypes.Where(f => publicDelegateTypes.Contains(f.Name)))
        {
            GenerateFunctionPointerTypeDelegate(sb, fpType);
        }

        // Generate remaining function pointer type delegates (legacy only)
        sb.AppendLine("#if !NET8_0_OR_GREATER");

        foreach (var fpType in api.FunctionPointerTypes.Where(f => !publicDelegateTypes.Contains(f.Name)))
        {
            GenerateFunctionPointerTypeDelegate(sb, fpType);
        }

        // Generate function delegates
        foreach (var func in api.Functions)
        {
            GenerateFunctionDelegate(sb, func);
        }

        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("    public unsafe partial class Secp256k1");
        sb.AppendLine("    {");

        // Generate symbol name constants
        sb.AppendLine("        // Native function symbol names");
        foreach (var func in api.Functions)
        {
            var symbolName = GetSymbolConstName(func.Name);
            sb.AppendLine($"        private const string {symbolName} = \"{func.Name}\";");
        }
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var symbolName = GetSymbolConstName(global.Name);
            sb.AppendLine($"        private const string {symbolName} = \"{global.Name}\";");
        }
        sb.AppendLine();

        // Modern .NET 8+ section with function pointers
        sb.AppendLine("#if NET8_0_OR_GREATER");
        GenerateModernFunctionPointers(sb, api, signatureToAlias);
        sb.AppendLine("#else");
        GenerateLegacyDelegates(sb, api);
        sb.AppendLine("#endif");

        // Generate LoadFunctions method
        sb.AppendLine();
        sb.AppendLine("        private static void LoadFunctions(IntPtr lib)");
        sb.AppendLine("        {");
        sb.AppendLine("#if NET8_0_OR_GREATER");
        GenerateModernLoadFunctions(sb, api, signatureToAlias);
        sb.AppendLine("#else");
        GenerateLegacyLoadFunctions(sb, api);
        sb.AppendLine("#endif");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private Dictionary<string, string> CollectFunctionPointerSignatures(Secp256k1Api api)
    {
        var signatureToAlias = new Dictionary<string, string>();
        var aliasCounter = 0;

        // Collect signatures from all functions
        foreach (var func in api.Functions)
        {
            var signature = GetModernFunctionPointerType(func);
            if (!signatureToAlias.ContainsKey(signature))
            {
                signatureToAlias[signature] = $"FnPtr{aliasCounter++}";
            }
        }

        // Collect signatures from global function pointers
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var signature = GetModernFunctionPointerTypeForGlobal(global, api);
            if (!signatureToAlias.ContainsKey(signature))
            {
                signatureToAlias[signature] = $"FnPtr{aliasCounter++}";
            }
        }

        return signatureToAlias;
    }

    private void GenerateModernFunctionPointers(StringBuilder sb, Secp256k1Api api, Dictionary<string, string> signatureToAlias)
    {
        sb.AppendLine("        // Function pointer declarations (modern .NET 8+)");
        sb.AppendLine("#nullable disable");

        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var funcPtrType = GetModernFunctionPointerType(func);
            var alias = signatureToAlias[funcPtrType];
            sb.AppendLine($"        private static {alias} {fieldName};");
        }

        // Global function pointer variables
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var funcPtrType = GetModernFunctionPointerTypeForGlobal(global, api);
            var alias = signatureToAlias[funcPtrType];
            sb.AppendLine($"        private static {alias} {fieldName};");
        }

        sb.AppendLine("#nullable restore");
    }

    private void GenerateLegacyDelegates(StringBuilder sb, Secp256k1Api api)
    {
        sb.AppendLine("        // Delegate instance fields (legacy .NET)");
        sb.AppendLine("#nullable disable");

        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var delegateType = func.Name;
            sb.AppendLine($"        private static {delegateType} {fieldName};");
        }

        // Global function pointer variables use their typedef type
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            sb.AppendLine($"        private static {global.Type} {fieldName};");
        }

        sb.AppendLine("#nullable restore");
    }

    private void GenerateModernLoadFunctions(StringBuilder sb, Secp256k1Api api, Dictionary<string, string> signatureToAlias)
    {
        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var symbolName = GetSymbolConstName(func.Name);
            var funcPtrType = GetModernFunctionPointerType(func);
            var alias = signatureToAlias[funcPtrType];

            sb.AppendLine($"            {fieldName} = ({alias})NativeLibrary.GetExport(lib, {symbolName});");
        }

        // Global function pointers are data symbols - need to read the pointer
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var symbolName = GetSymbolConstName(global.Name);
            var funcPtrType = GetModernFunctionPointerTypeForGlobal(global, api);
            var alias = signatureToAlias[funcPtrType];

            sb.AppendLine();
            sb.AppendLine($"            // {global.Name} is a data symbol (function pointer), not a function");
            sb.AppendLine($"            var {fieldName}Ptr = NativeLibrary.GetExport(lib, {symbolName});");
            sb.AppendLine($"            {fieldName} = ({alias})Marshal.ReadIntPtr({fieldName}Ptr);");
        }
    }

    private void GenerateLegacyLoadFunctions(StringBuilder sb, Secp256k1Api api)
    {
        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var symbolName = GetSymbolConstName(func.Name);
            var delegateType = func.Name;

            sb.AppendLine($"            {fieldName} = LoadLibNative.GetDelegate<{delegateType}>(lib, {symbolName});");
        }

        // Global function pointers are data symbols
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var symbolName = GetSymbolConstName(global.Name);

            sb.AppendLine();
            sb.AppendLine($"            // {global.Name} is a data symbol (function pointer), not a function");
            sb.AppendLine($"            {fieldName} = LoadLibNative.GetDelegate<{global.Type}>(lib, {symbolName}, Marshal.ReadIntPtr);");
        }
    }

    private string GetModernFunctionPointerType(FunctionDef func)
    {
        var returnType = MapCTypeToCSharpForFunctionPointer(func.ReturnType);

        var paramTypes = func.Parameters.Select(p => MapCTypeToCSharpForFunctionPointer(p.Type, p.Name)).ToList();

        if (paramTypes.Count == 0)
        {
            return $"delegate* unmanaged[Cdecl]<{returnType}>";
        }

        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", paramTypes)}, {returnType}>";
    }

    private string GetModernFunctionPointerTypeForGlobal(GlobalPointer global, Secp256k1Api api)
    {
        // Find the function pointer type definition
        var fpType = api.FunctionPointerTypes.FirstOrDefault(f => f.Name == global.Type);
        if (fpType == null)
        {
            // Fallback - return a generic function pointer
            return "delegate* unmanaged[Cdecl]<int>";
        }

        var returnType = MapCTypeToCSharpForFunctionPointer(fpType.ReturnType);
        var paramTypes = fpType.Parameters.Select(p => MapCTypeToCSharpForFunctionPointer(p.Type, p.Name)).ToList();

        if (paramTypes.Count == 0)
        {
            return $"delegate* unmanaged[Cdecl]<{returnType}>";
        }

        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", paramTypes)}, {returnType}>";
    }

    private string MapCTypeToCSharp(string cType, string? paramName = null)
    {
        cType = cType.Trim();

        // Handle inline function pointer types like "void (*)(const char*, void*)"
        if (cType.Contains("(*)"))
            return "IntPtr";

        // Handle specific secp256k1 types
        // Note: check for "secp256k1_context" with Contains() to handle "const secp256k1_context*"
        if (cType.Contains("secp256k1_context") && cType.Contains("*"))
            return "IntPtr";
        if (cType == "secp256k1_context")
            return "IntPtr";

        // Function pointer types as parameters
        if (cType.Contains("secp256k1_") && cType.Contains("function"))
            return "IntPtr";

        // Handle pointer types
        // Double pointers (** or "* const*" pattern) become IntPtr
        if (cType.EndsWith("**") || cType.Contains("* const*") || cType.Contains("**"))
            return "IntPtr";

        if (cType.Contains("*"))
        {

            // Most pointer types become void*
            if (cType.Contains("unsigned char") || cType.Contains("char"))
                return "void*";
            if (cType.Contains("secp256k1_"))
                return "void*";
            if (cType.Contains("void"))
                return "void*";
            if (cType.Contains("size_t"))
                return "nuint*";
            if (cType.Contains("int") && !cType.Contains("uint"))
                return "int*";

            return "void*";
        }

        // Non-pointer types
        return cType switch
        {
            "unsigned int" => "uint",
            "int" => "int",
            "size_t" => "nuint",
            "uint64_t" => "ulong",
            "int64_t" => "long",
            "uint32_t" => "uint",
            "int32_t" => "int",
            "void" => "void",
            _ => cType
        };
    }

    private string MapCTypeToCSharpForFunctionPointer(string cType, string? paramName = null)
    {
        cType = cType.Trim();

        // Handle inline function pointer types like "void (*)(const char*, void*)"
        if (cType.Contains("(*)"))
            return "IntPtr";

        // Handle specific secp256k1 types
        // Note: check for "secp256k1_context" with Contains() to handle "const secp256k1_context*"
        if (cType.Contains("secp256k1_context") && cType.Contains("*"))
            return "IntPtr";
        if (cType == "secp256k1_context")
            return "IntPtr";

        // Function pointer types as parameters
        if (cType.Contains("secp256k1_") && cType.Contains("function"))
            return "IntPtr";

        // Handle pointer types
        // Double pointers (** or "* const*" pattern) become IntPtr
        if (cType.EndsWith("**") || cType.Contains("* const*") || cType.Contains("**"))
            return "IntPtr";

        if (cType.Contains("*"))
        {

            if (cType.Contains("unsigned char") || cType.Contains("char"))
                return "void*";
            if (cType.Contains("secp256k1_"))
                return "void*";
            if (cType.Contains("void"))
                return "void*";
            if (cType.Contains("size_t"))
                return "nuint*";
            if (cType.Contains("int") && !cType.Contains("uint"))
                return "int*";

            return "void*";
        }

        // Non-pointer types
        return cType switch
        {
            "unsigned int" => "uint",
            "int" => "int",
            "size_t" => "nuint",
            "uint64_t" => "ulong",
            "int64_t" => "long",
            "uint32_t" => "uint",
            "int32_t" => "int",
            "void" => "void",
            _ => cType
        };
    }

    private static string GetFieldName(string functionName)
    {
        // secp256k1_context_create -> _context_create
        if (functionName.StartsWith("secp256k1_"))
        {
            return "_" + functionName.Substring("secp256k1_".Length);
        }
        return "_" + functionName;
    }

    private static string GetSymbolConstName(string functionName)
    {
        // secp256k1_context_create -> SYM_context_create
        if (functionName.StartsWith("secp256k1_"))
        {
            return "SYM_" + functionName.Substring("secp256k1_".Length);
        }
        return "SYM_" + functionName;
    }

    private static string SanitizeParamName(string name)
    {
        // Handle C# reserved words
        return name switch
        {
            "data" => "data",
            "output" => "output",
            "input" => "input",
            "in" => "@in",
            "out" => "@out",
            "ref" => "@ref",
            _ => name
        };
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");
    }

    private static string CleanDescription(string? text)
    {
        if (text is null || text.Length == 0)
            return "";

        // Remove C comment markers and clean up
        var result = text
            .Replace("\r", "")
            .Replace("/**", "")
            .Replace("*/", "")
            .Replace("\n * ", "\n")  // Convert " * " line prefix to just newline
            .Replace("\n *", "\n");  // Handle " *" without trailing space

        // Clean up multiple consecutive newlines
        while (result.Contains("\n\n\n"))
            result = result.Replace("\n\n\n", "\n\n");

        return result.Trim();
    }

    /// <summary>
    /// Formats a description for XML documentation, handling multi-line text.
    /// Uses para tags to create proper paragraph breaks that IntelliSense will render.
    /// </summary>
    private static string FormatXmlDescription(string? text)
    {
        if (text is null || text.Length == 0)
            return "";

        var cleaned = CleanDescription(text);
        var escaped = EscapeXml(cleaned);

        // If single line, return as-is
        if (!escaped.Contains('\n'))
            return escaped;

        // Split into paragraphs (separated by blank lines) and lines within paragraphs
        var paragraphs = new List<string>();
        var currentParagraph = new List<string>();

        foreach (var line in escaped.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                if (currentParagraph.Count > 0)
                {
                    paragraphs.Add(string.Join(" ", currentParagraph));
                    currentParagraph.Clear();
                }
            }
            else
            {
                currentParagraph.Add(line.Trim());
            }
        }

        if (currentParagraph.Count > 0)
        {
            paragraphs.Add(string.Join(" ", currentParagraph));
        }

        // If only one paragraph, return as single line
        if (paragraphs.Count == 1)
            return paragraphs[0];

        // Multiple paragraphs - use <para> tags for proper IntelliSense rendering
        var result = new StringBuilder();
        for (int i = 0; i < paragraphs.Count; i++)
        {
            if (i == 0)
            {
                // First paragraph without para tag
                result.Append(paragraphs[i]);
            }
            else
            {
                // Subsequent paragraphs with para tags
                result.Append($"<para>{paragraphs[i]}</para>");
            }
        }

        return result.ToString();
    }

    // JSON model classes
    private class Secp256k1Api
    {
        public string Version { get; set; } = "";
        public string GeneratedAt { get; set; } = "";
        public List<string> Headers { get; set; } = new();
        public List<StructDef> Structs { get; set; } = new();
        public List<FunctionPointerType> FunctionPointerTypes { get; set; } = new();
        public List<FunctionDef> Functions { get; set; } = new();
        public List<ConstantDef> Constants { get; set; } = new();
        public List<GlobalPointer> GlobalPointers { get; set; } = new();
    }

    private class StructDef
    {
        public string Name { get; set; } = "";
        public int Size { get; set; }
        public string? Description { get; set; }
    }

    private class FunctionPointerType
    {
        public string Name { get; set; } = "";
        public string ReturnType { get; set; } = "";
        public List<ParameterDef> Parameters { get; set; } = new();
        public string? Description { get; set; }
    }

    private class FunctionDef
    {
        public string Name { get; set; } = "";
        public string ReturnType { get; set; } = "";
        public bool WarnUnusedResult { get; set; }
        public bool Deprecated { get; set; }
        public string? DeprecatedMessage { get; set; }
        public List<ParameterDef> Parameters { get; set; } = new();
        public string? Description { get; set; }
        public string? ReturnDescription { get; set; }
        public string? SourceHeader { get; set; }
    }

    private class ParameterDef
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
        public string? Direction { get; set; }
        public bool Nonnull { get; set; }
        public string? Description { get; set; }
    }

    private class ConstantDef
    {
        public string Name { get; set; } = "";
        public string Value { get; set; } = "";
        public long? NumericValue { get; set; }
        public string? Description { get; set; }
    }

    private class GlobalPointer
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
        public bool IsConst { get; set; }
        public string? Description { get; set; }
    }

    #region Wrapper Generation

    // Functions to skip in wrapper generation (need manual implementation or are internal)
    private static readonly HashSet<string> SkipWrapperFunctions = new()
    {
        "secp256k1_context_create",
        "secp256k1_context_clone",
        "secp256k1_context_destroy",
        "secp256k1_context_set_illegal_callback",
        "secp256k1_context_set_error_callback",
        "secp256k1_context_randomize",
        "secp256k1_context_preallocated_size",
        "secp256k1_context_preallocated_create",
        "secp256k1_context_preallocated_clone_size",
        "secp256k1_context_preallocated_clone",
        "secp256k1_context_preallocated_destroy",
        // Functions with array-of-pointers that need manual handling
        "secp256k1_ec_pubkey_combine",
        "secp256k1_musig_pubkey_agg",
        "secp256k1_musig_nonce_agg",
        "secp256k1_musig_partial_sig_agg",
    };

    // Struct sizes from JSON (secp256k1 opaque types)
    private static readonly Dictionary<string, int> StructSizes = new()
    {
        ["secp256k1_pubkey"] = 64,
        ["secp256k1_ecdsa_signature"] = 64,
        ["secp256k1_ecdsa_recoverable_signature"] = 65,
        ["secp256k1_xonly_pubkey"] = 64,
        ["secp256k1_keypair"] = 96,
        ["secp256k1_musig_keyagg_cache"] = 197,
        ["secp256k1_musig_secnonce"] = 132,
        ["secp256k1_musig_pubnonce"] = 132,
        ["secp256k1_musig_aggnonce"] = 132,
        ["secp256k1_musig_session"] = 133,
        ["secp256k1_musig_partial_sig"] = 36,
    };

    private string GenerateWrappers(Secp256k1Api api)
    {
        // Update struct sizes from JSON if available
        var structSizes = new Dictionary<string, int>(StructSizes);
        foreach (var s in api.Structs.Where(s => s.Size > 0))
        {
            structSizes[s.Name] = s.Size;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Secp256k1Net");
        sb.AppendLine("{");
        sb.AppendLine("    public unsafe partial class Secp256k1");
        sb.AppendLine("    {");

        foreach (var func in api.Functions.Where(f => !SkipWrapperFunctions.Contains(f.Name) && !f.Deprecated))
        {
            GenerateWrapperMethod(sb, func, structSizes);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateWrapperMethod(StringBuilder sb, FunctionDef func, Dictionary<string, int> structSizes)
    {
        // Skip if any parameter has a double-pointer or array-of-pointers type
        if (func.Parameters.Any(p => p.Type.Contains("**") || p.Type.Contains("* const*")))
        {
            return;
        }

        // Skip if has function pointer parameter (callback) - these need manual implementation
        if (func.Parameters.Any(p => p.Type.Contains("function") || p.Type.Contains("(*)")))
        {
            return;
        }

        var methodName = GetWrapperMethodName(func.Name);
        var parameters = GetWrapperParameters(func, structSizes);
        var hasContextParam = func.Parameters.FirstOrDefault()?.Type.Contains("secp256k1_context") == true;

        // Skip context parameter in wrapper signature
        var wrapperParams = hasContextParam ? parameters.Skip(1).ToList() : parameters.ToList();

        // Generate XML documentation
        sb.AppendLine();
        if (!string.IsNullOrEmpty(func.Description))
        {
            sb.AppendLine($"        /// <summary>{FormatXmlDescription(func.Description)}</summary>");
        }

        foreach (var param in wrapperParams)
        {
            if (!string.IsNullOrEmpty(param.Description))
            {
                // XML param names don't use @ prefix
                var xmlParamName = param.WrapperName.TrimStart('@');
                sb.AppendLine($"        /// <param name=\"{xmlParamName}\">{FormatXmlDescription(param.Description)}</param>");
            }
        }

        if (!string.IsNullOrEmpty(func.ReturnDescription))
        {
            sb.AppendLine($"        /// <returns>{FormatXmlDescription(func.ReturnDescription)}</returns>");
        }

        // Determine return type
        var returnsBool = func.ReturnType == "int";
        var returnType = returnsBool ? "bool" : MapCTypeToCSharp(func.ReturnType);

        // Method signature
        var paramSignature = string.Join(", ", wrapperParams.Select(p => $"{p.WrapperType} {p.WrapperName}"));
        sb.AppendLine($"        public {returnType} {methodName}({paramSignature})");
        sb.AppendLine("        {");

        // Generate validation
        foreach (var param in wrapperParams.Where(p => p.RequiredSize > 0 && p.IsSpan))
        {
            sb.AppendLine($"            if ({param.WrapperName}.Length < {param.RequiredSize})");
            sb.AppendLine($"                throw new ArgumentException($\"{{nameof({param.WrapperName})}} must be at least {param.RequiredSize} bytes\");");
        }

        // Collect span parameters for fixed statement
        var spanParams = wrapperParams.Where(p => p.IsSpan).ToList();
        var refParams = wrapperParams.Where(p => p.IsRefParam).ToList();

        var needsFixed = spanParams.Count > 0 || refParams.Count > 0;

        if (needsFixed)
        {
            sb.AppendLine();

            // Build fixed statement for byte spans
            if (spanParams.Count > 0)
            {
                var fixedDeclarations = spanParams.Select(p =>
                    $"{p.WrapperName}Ptr = &MemoryMarshal.GetReference({p.WrapperName})");
                sb.AppendLine($"            fixed (byte* {string.Join(",\n                ", fixedDeclarations)})");
            }

            // Build fixed statement for ref params
            foreach (var refParam in refParams)
            {
                var cleanName = refParam.WrapperName.TrimStart('@');
                sb.AppendLine($"            fixed ({refParam.RefParamType}* {cleanName}Ptr = &{refParam.WrapperName})");
            }

            sb.AppendLine("            {");

            // Build native call
            var nativeArgs = BuildNativeCallArgs(func, wrapperParams, hasContextParam);
            var fieldName = GetFieldName(func.Name);

            if (returnsBool)
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs}) == 1;");
            }
            else if (func.ReturnType == "void")
            {
                sb.AppendLine($"                {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs});");
            }

            sb.AppendLine("            }");
        }
        else
        {
            // No span or ref parameters - direct call
            var nativeArgs = BuildNativeCallArgs(func, wrapperParams, hasContextParam);
            var fieldName = GetFieldName(func.Name);

            if (returnsBool)
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs}) == 1;");
            }
            else if (func.ReturnType == "void")
            {
                sb.AppendLine($"            {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs});");
            }
        }

        sb.AppendLine("        }");
    }

    private List<WrapperParameter> GetWrapperParameters(FunctionDef func, Dictionary<string, int> structSizes)
    {
        var result = new List<WrapperParameter>();

        foreach (var param in func.Parameters)
        {
            var wrapper = new WrapperParameter
            {
                OriginalName = param.Name,
                OriginalType = param.Type,
                Direction = param.Direction ?? "in",
                Description = param.Description
            };

            // Determine wrapper type and size
            DetermineWrapperType(wrapper, param, structSizes);

            result.Add(wrapper);
        }

        return result;
    }

    private void DetermineWrapperType(WrapperParameter wrapper, ParameterDef param, Dictionary<string, int> structSizes)
    {
        var cType = param.Type.Trim();
        var name = param.Name;
        var direction = param.Direction ?? "in";

        // Context pointer - use IntPtr internally
        if (cType.Contains("secp256k1_context"))
        {
            wrapper.WrapperType = "IntPtr";
            wrapper.WrapperName = "_ctx";
            wrapper.IsContextParam = true;
            return;
        }

        // Function pointer types
        if (cType.Contains("function") || cType.Contains("(*)"))
        {
            wrapper.WrapperType = "IntPtr";
            wrapper.WrapperName = SanitizeParamName(name);
            return;
        }

        // Size_t pointer (output length) - treat as ref parameter that needs fixed
        if (cType.Contains("size_t") && cType.Contains("*"))
        {
            wrapper.WrapperType = "ref nuint";
            wrapper.WrapperName = SanitizeParamName(name);
            wrapper.IsRefParam = true;
            wrapper.RefParamType = "nuint";
            return;
        }

        // Int pointer (e.g., recid) - treat as ref/out parameter that needs fixed
        if (cType.Contains("int") && cType.Contains("*") && !cType.Contains("uint"))
        {
            wrapper.WrapperType = direction == "out" ? "out int" : "ref int";
            wrapper.WrapperName = SanitizeParamName(name);
            wrapper.IsRefParam = true;
            wrapper.RefParamType = "int";
            return;
        }

        // Non-pointer primitive types
        if (!cType.Contains("*"))
        {
            wrapper.WrapperType = MapCTypeToCSharp(cType);
            wrapper.WrapperName = SanitizeParamName(name);
            return;
        }

        // Pointer types - determine if they should be Span<byte> or ReadOnlySpan<byte>
        wrapper.IsSpan = true;

        // Determine span type based on direction and const
        bool isInput = direction == "in" || cType.StartsWith("const ");
        wrapper.WrapperType = isInput ? "ReadOnlySpan<byte>" : "Span<byte>";
        wrapper.WrapperName = GetWrapperParamName(name);

        // Determine required size
        wrapper.RequiredSize = GetRequiredSize(cType, name, structSizes);
    }

    private int GetRequiredSize(string cType, string paramName, Dictionary<string, int> structSizes)
    {
        // Check if it's a known struct type
        foreach (var kvp in structSizes)
        {
            if (cType.Contains(kvp.Key))
            {
                return kvp.Value;
            }
        }

        // Check parameter name patterns
        if (paramName.EndsWith("32") || paramName.Contains("msg32") || paramName.Contains("seckey") ||
            paramName.Contains("tweak") || paramName.Contains("seed32") || paramName.Contains("hash32") ||
            paramName.Contains("nonce32") || paramName.Contains("key32") || paramName.Contains("aux_rand32") ||
            paramName.Contains("auxrnd32") || paramName.Contains("xonly_pk32"))
        {
            return 32;
        }

        if (paramName.EndsWith("33") || paramName.Contains("pubkey33"))
        {
            return 33;
        }

        if (paramName.EndsWith("64") || paramName.Contains("sig64") || paramName.Contains("ell64"))
        {
            return 64;
        }

        if (paramName.EndsWith("65") || paramName.Contains("pubkey65"))
        {
            return 65;
        }

        // Default - no size validation
        return 0;
    }

    private string GetWrapperMethodName(string functionName)
    {
        // secp256k1_ec_pubkey_create -> EcPubkeyCreate
        var name = functionName;

        // Remove secp256k1_ prefix
        if (name.StartsWith("secp256k1_"))
        {
            name = name.Substring("secp256k1_".Length);
        }

        // Convert snake_case to PascalCase
        var parts = name.Split('_');
        var result = string.Join("", parts.Select(p =>
            p.Length > 0 ? char.ToUpper(p[0]) + p.Substring(1).ToLower() : ""));

        // Handle common acronyms
        result = result.Replace("Ecdsa", "Ecdsa")
                       .Replace("Ecdh", "Ecdh")
                       .Replace("Ec", "Ec");

        return result;
    }

    private string GetWrapperParamName(string originalName)
    {
        // Convert C-style names to C# style
        var name = originalName;

        // Remove common suffixes for cleaner names
        if (name.EndsWith("32") || name.EndsWith("33") || name.EndsWith("64") || name.EndsWith("65"))
        {
            // Keep the suffix in the name for clarity
        }

        return SanitizeParamName(name);
    }

    private static string BuildNativeCallArgs(FunctionDef func, List<WrapperParameter> wrapperParams, bool hasContextParam)
    {
        var args = new List<string>();

        if (hasContextParam)
        {
            args.Add("_ctx");
        }

        foreach (var param in wrapperParams)
        {
            if (param.IsSpan)
            {
                args.Add($"{param.WrapperName}Ptr");
            }
            else if (param.IsRefParam)
            {
                // Use the pinned pointer variable
                var cleanName = param.WrapperName.TrimStart('@');
                args.Add($"{cleanName}Ptr");
            }
            else
            {
                args.Add(param.WrapperName);
            }
        }

        return string.Join(", ", args);
    }

    private class WrapperParameter
    {
        public string OriginalName { get; set; } = "";
        public string OriginalType { get; set; } = "";
        public string WrapperType { get; set; } = "";
        public string WrapperName { get; set; } = "";
        public string Direction { get; set; } = "in";
        public string? Description { get; set; }
        public int RequiredSize { get; set; }
        public bool IsSpan { get; set; }
        public bool IsContextParam { get; set; }
        public bool IsRefParam { get; set; }
        public string RefParamType { get; set; } = "";
    }

    #endregion
}
