<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- net462 is the recommended minimum .NET Framework version for netstandard2.0 -->
    <TargetFramework>net462</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Secp256k1.Net" Version="0.0.1-localtest.1" />
  </ItemGroup>

</Project>
