using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Secp256k1Net.InteropGen;

public class InteropGenerator
{
    public string GenerateNative(Secp256k1Api api)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();

        // Collect all unique function pointer signatures and generate type aliases (inside namespace, after using System)
        var signatureToAlias = CollectFunctionPointerSignatures(api);

        sb.AppendLine("#if NET8_0_OR_GREATER");
        foreach (var kvp in signatureToAlias.OrderBy(x => x.Value))
        {
            // Use fully-qualified System.IntPtr in using aliases since they're processed before using System;
            var fullyQualifiedSignature = kvp.Key.Replace("IntPtr", "System.IntPtr");
            sb.AppendLine($"using unsafe {kvp.Value} = {fullyQualifiedSignature};");
        }
        sb.AppendLine("#endif");
        sb.AppendLine();

        sb.AppendLine("namespace Secp256k1Net");
        sb.AppendLine("{");

        // Generate function pointer type delegates that are used in public/internal APIs (available for all targets)
        // These are needed for callback marshaling - must be available for both legacy and modern targets
        var publicDelegateTypes = new HashSet<string>
        {
            "secp256k1_ecdh_hash_function",
            "secp256k1_nonce_function",
            "secp256k1_nonce_function_hardened",
            "secp256k1_ellswift_xdh_hash_function",
        };
        foreach (var fpType in api.FunctionPointerTypes.Where(f => publicDelegateTypes.Contains(f.Name)))
        {
            GenerateFunctionPointerTypeDelegate(sb, fpType);
        }

        // Generate remaining function pointer type delegates (legacy only)
        sb.AppendLine("#if !NET8_0_OR_GREATER");

        foreach (var fpType in api.FunctionPointerTypes.Where(f => !publicDelegateTypes.Contains(f.Name)))
        {
            GenerateFunctionPointerTypeDelegate(sb, fpType);
        }

        // Generate function delegates
        foreach (var func in api.Functions)
        {
            GenerateFunctionDelegate(sb, func);
        }

        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("    public unsafe partial class Secp256k1");
        sb.AppendLine("    {");

        // Generate symbol name constants
        sb.AppendLine("        // Native function symbol names");
        foreach (var func in api.Functions)
        {
            var symbolName = GetSymbolConstName(func.Name);
            sb.AppendLine($"        private const string {symbolName} = \"{func.Name}\";");
        }
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var symbolName = GetSymbolConstName(global.Name);
            sb.AppendLine($"        private const string {symbolName} = \"{global.Name}\";");
        }
        sb.AppendLine();

        // Modern .NET 8+ section with function pointers
        sb.AppendLine("#if NET8_0_OR_GREATER");
        GenerateModernFunctionPointers(sb, api, signatureToAlias);
        sb.AppendLine("#else");
        GenerateLegacyDelegates(sb, api);
        sb.AppendLine("#endif");

        // Generate LoadFunctions method
        sb.AppendLine();
        sb.AppendLine("        private static void LoadFunctions(IntPtr lib)");
        sb.AppendLine("        {");
        sb.AppendLine("#if NET8_0_OR_GREATER");
        GenerateModernLoadFunctions(sb, api, signatureToAlias);
        sb.AppendLine("#else");
        GenerateLegacyLoadFunctions(sb, api);
        sb.AppendLine("#endif");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateFunctionPointerTypeDelegate(StringBuilder sb, FunctionPointerType fpType)
    {
        sb.AppendLine();
        if (!string.IsNullOrEmpty(fpType.Description))
        {
            sb.AppendLine($"    /// <summary>{FormatXmlDescription(fpType.Description)}</summary>");
        }
        sb.AppendLine("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");

        var returnType = MapCTypeToCSharp(fpType.ReturnType);
        var hasPointerParams = fpType.Parameters.Any(p => p.Type.Contains("*"));

        sb.Append($"    public {(hasPointerParams ? "unsafe " : "")}delegate {returnType} {fpType.Name}(");

        var paramStrings = fpType.Parameters.Select(p =>
        {
            var csType = MapCTypeToCSharp(p.Type, p.Name);
            return $"{csType} {SanitizeParamName(p.Name)}";
        });

        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");
    }

    private void GenerateFunctionDelegate(StringBuilder sb, FunctionDef func)
    {
        sb.AppendLine();
        if (!string.IsNullOrEmpty(func.Description))
        {
            sb.AppendLine($"    /// <summary>{FormatXmlDescription(func.Description)}</summary>");
        }

        foreach (var param in func.Parameters)
        {
            // Always generate param tags to avoid CS1573 warnings
            var description = FormatXmlDescription(param.Description);
            sb.AppendLine($"    /// <param name=\"{param.Name}\">{description}</param>");
        }

        if (!string.IsNullOrEmpty(func.ReturnDescription))
        {
            sb.AppendLine($"    /// <returns>{FormatXmlDescription(func.ReturnDescription)}</returns>");
        }

        var returnType = MapCTypeToCSharp(func.ReturnType);
        var hasPointerParams = func.Parameters.Any(p => p.Type.Contains("*"));

        // Create delegate name from function name
        var delegateName = func.Name;

        sb.Append($"    public {(hasPointerParams ? "unsafe " : "")}delegate {returnType} {delegateName}(");

        var paramStrings = func.Parameters.Select(p =>
        {
            var csType = MapCTypeToCSharp(p.Type, p.Name);
            var paramName = SanitizeParamName(p.Name);
            return $"{csType} {paramName}";
        });

        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");
    }

    private Dictionary<string, string> CollectFunctionPointerSignatures(Secp256k1Api api)
    {
        var signatureToAlias = new Dictionary<string, string>();
        var aliasCounter = 0;

        // Collect signatures from all functions
        foreach (var func in api.Functions)
        {
            var signature = GetModernFunctionPointerType(func);
            if (!signatureToAlias.ContainsKey(signature))
            {
                signatureToAlias[signature] = $"FnPtr{aliasCounter++:D2}";
            }
        }

        // Collect signatures from global function pointers
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var signature = GetModernFunctionPointerTypeForGlobal(global, api);
            if (!signatureToAlias.ContainsKey(signature))
            {
                signatureToAlias[signature] = $"FnPtr{aliasCounter++:D2}";
            }
        }

        return signatureToAlias;
    }

    private void GenerateModernFunctionPointers(StringBuilder sb, Secp256k1Api api, Dictionary<string, string> signatureToAlias)
    {
        sb.AppendLine("        // Function pointer declarations (modern .NET 8+)");
        sb.AppendLine("#nullable disable");

        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var funcPtrType = GetModernFunctionPointerType(func);
            var alias = signatureToAlias[funcPtrType];
            sb.AppendLine($"        private static {alias} {fieldName};");
        }

        // Global function pointer variables
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var funcPtrType = GetModernFunctionPointerTypeForGlobal(global, api);
            var alias = signatureToAlias[funcPtrType];
            sb.AppendLine($"        private static {alias} {fieldName};");
        }

        sb.AppendLine("#nullable restore");
    }

    private void GenerateLegacyDelegates(StringBuilder sb, Secp256k1Api api)
    {
        sb.AppendLine("        // Delegate instance fields (legacy .NET)");
        sb.AppendLine("#nullable disable");

        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var delegateType = func.Name;
            sb.AppendLine($"        private static {delegateType} {fieldName};");
        }

        // Global function pointer variables use their typedef type
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            sb.AppendLine($"        private static {global.Type} {fieldName};");
        }

        sb.AppendLine("#nullable restore");
    }

    private void GenerateModernLoadFunctions(StringBuilder sb, Secp256k1Api api, Dictionary<string, string> signatureToAlias)
    {
        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var symbolName = GetSymbolConstName(func.Name);
            var funcPtrType = GetModernFunctionPointerType(func);
            var alias = signatureToAlias[funcPtrType];

            sb.AppendLine($"            {fieldName} = ({alias})NativeLibrary.GetExport(lib, {symbolName});");
        }

        // Global function pointers are data symbols - need to read the pointer
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var symbolName = GetSymbolConstName(global.Name);
            var funcPtrType = GetModernFunctionPointerTypeForGlobal(global, api);
            var alias = signatureToAlias[funcPtrType];

            sb.AppendLine();
            sb.AppendLine($"            // {global.Name} is a data symbol (function pointer), not a function");
            sb.AppendLine($"            var {fieldName}Ptr = NativeLibrary.GetExport(lib, {symbolName});");
            sb.AppendLine($"            {fieldName} = ({alias})Marshal.ReadIntPtr({fieldName}Ptr);");
        }
    }

    private void GenerateLegacyLoadFunctions(StringBuilder sb, Secp256k1Api api)
    {
        foreach (var func in api.Functions)
        {
            var fieldName = GetFieldName(func.Name);
            var symbolName = GetSymbolConstName(func.Name);
            var delegateType = func.Name;

            sb.AppendLine($"            {fieldName} = LoadLibNative.GetDelegate<{delegateType}>(lib, {symbolName});");
        }

        // Global function pointers are data symbols
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            var fieldName = GetFieldName(global.Name);
            var symbolName = GetSymbolConstName(global.Name);

            sb.AppendLine();
            sb.AppendLine($"            // {global.Name} is a data symbol (function pointer), not a function");
            sb.AppendLine($"            {fieldName} = LoadLibNative.GetDelegate<{global.Type}>(lib, {symbolName}, Marshal.ReadIntPtr);");
        }
    }

    private string GetModernFunctionPointerType(FunctionDef func)
    {
        var returnType = MapCTypeToCSharpForFunctionPointer(func.ReturnType);

        var paramTypes = func.Parameters.Select(p => MapCTypeToCSharpForFunctionPointer(p.Type, p.Name)).ToList();

        if (paramTypes.Count == 0)
        {
            return $"delegate* unmanaged[Cdecl]<{returnType}>";
        }

        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", paramTypes)}, {returnType}>";
    }

    private string GetModernFunctionPointerTypeForGlobal(GlobalPointer global, Secp256k1Api api)
    {
        // Find the function pointer type definition
        var fpType = api.FunctionPointerTypes.FirstOrDefault(f => f.Name == global.Type);
        if (fpType == null)
        {
            // Fallback - return a generic function pointer
            return "delegate* unmanaged[Cdecl]<int>";
        }

        var returnType = MapCTypeToCSharpForFunctionPointer(fpType.ReturnType);
        var paramTypes = fpType.Parameters.Select(p => MapCTypeToCSharpForFunctionPointer(p.Type, p.Name)).ToList();

        if (paramTypes.Count == 0)
        {
            return $"delegate* unmanaged[Cdecl]<{returnType}>";
        }

        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", paramTypes)}, {returnType}>";
    }

    private string MapCTypeToCSharp(string cType, string? paramName = null)
    {
        cType = cType.Trim();

        // Handle inline function pointer types like "void (*)(const char*, void*)"
        if (cType.Contains("(*)"))
            return "IntPtr";

        // Handle specific secp256k1 types
        // Note: check for "secp256k1_context" with Contains() to handle "const secp256k1_context*"
        if (cType.Contains("secp256k1_context") && cType.Contains("*"))
            return "IntPtr";
        if (cType == "secp256k1_context")
            return "IntPtr";

        // Function pointer types as parameters
        if (cType.Contains("secp256k1_") && cType.Contains("function"))
            return "IntPtr";

        // Handle pointer types
        // Double pointers (** or "* const*" pattern) become IntPtr
        if (cType.EndsWith("**") || cType.Contains("* const*") || cType.Contains("**"))
            return "IntPtr";

        if (cType.Contains("*"))
        {

            // Most pointer types become void*
            if (cType.Contains("unsigned char") || cType.Contains("char"))
                return "void*";
            if (cType.Contains("secp256k1_"))
                return "void*";
            if (cType.Contains("void"))
                return "void*";
            if (cType.Contains("size_t"))
                return "nuint*";
            if (cType.Contains("int") && !cType.Contains("uint"))
                return "int*";

            return "void*";
        }

        // Non-pointer types
        return cType switch
        {
            "unsigned int" => "uint",
            "int" => "int",
            "size_t" => "nuint",
            "uint64_t" => "ulong",
            "int64_t" => "long",
            "uint32_t" => "uint",
            "int32_t" => "int",
            "void" => "void",
            _ => cType
        };
    }

    private string MapCTypeToCSharpForFunctionPointer(string cType, string? paramName = null)
    {
        cType = cType.Trim();

        // Handle inline function pointer types like "void (*)(const char*, void*)"
        if (cType.Contains("(*)"))
            return "IntPtr";

        // Handle specific secp256k1 types
        // Note: check for "secp256k1_context" with Contains() to handle "const secp256k1_context*"
        if (cType.Contains("secp256k1_context") && cType.Contains("*"))
            return "IntPtr";
        if (cType == "secp256k1_context")
            return "IntPtr";

        // Function pointer types as parameters
        if (cType.Contains("secp256k1_") && cType.Contains("function"))
            return "IntPtr";

        // Handle pointer types
        // Double pointers (** or "* const*" pattern) become IntPtr
        if (cType.EndsWith("**") || cType.Contains("* const*") || cType.Contains("**"))
            return "IntPtr";

        if (cType.Contains("*"))
        {

            if (cType.Contains("unsigned char") || cType.Contains("char"))
                return "void*";
            if (cType.Contains("secp256k1_"))
                return "void*";
            if (cType.Contains("void"))
                return "void*";
            if (cType.Contains("size_t"))
                return "nuint*";
            if (cType.Contains("int") && !cType.Contains("uint"))
                return "int*";

            return "void*";
        }

        // Non-pointer types
        return cType switch
        {
            "unsigned int" => "uint",
            "int" => "int",
            "size_t" => "nuint",
            "uint64_t" => "ulong",
            "int64_t" => "long",
            "uint32_t" => "uint",
            "int32_t" => "int",
            "void" => "void",
            _ => cType
        };
    }

    private static string GetFieldName(string functionName)
    {
        // secp256k1_context_create -> _context_create
        if (functionName.StartsWith("secp256k1_"))
        {
            return "_" + functionName.Substring("secp256k1_".Length);
        }
        return "_" + functionName;
    }

    private static string GetSymbolConstName(string functionName)
    {
        // secp256k1_context_create -> SYM_context_create
        if (functionName.StartsWith("secp256k1_"))
        {
            return "SYM_" + functionName.Substring("secp256k1_".Length);
        }
        return "SYM_" + functionName;
    }

    private static string SanitizeParamName(string name)
    {
        // Handle C# reserved words
        return name switch
        {
            "data" => "data",
            "output" => "output",
            "input" => "input",
            "in" => "@in",
            "out" => "@out",
            "ref" => "@ref",
            _ => name
        };
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");
    }

    private static string CleanDescription(string? text)
    {
        if (text is null || text.Length == 0)
            return "";

        // Remove C comment markers and clean up
        var result = text
            .Replace("\r", "")
            .Replace("/**", "")
            .Replace("*/", "")
            .Replace("\n * ", "\n")  // Convert " * " line prefix to just newline
            .Replace("\n *", "\n");  // Handle " *" without trailing space

        // Clean up multiple consecutive newlines
        while (result.Contains("\n\n\n"))
            result = result.Replace("\n\n\n", "\n\n");

        return result.Trim();
    }

    /// <summary>
    /// Formats a description for XML documentation, handling multi-line text.
    /// Uses para tags to create proper paragraph breaks that IntelliSense will render.
    /// </summary>
    private static string FormatXmlDescription(string? text)
    {
        if (text is null || text.Length == 0)
            return "";

        var cleaned = CleanDescription(text);
        var escaped = EscapeXml(cleaned);

        // If single line, return as-is
        if (!escaped.Contains('\n'))
            return escaped;

        // Split into paragraphs (separated by blank lines) and lines within paragraphs
        var paragraphs = new List<string>();
        var currentParagraph = new List<string>();

        foreach (var line in escaped.Split('\n'))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                if (currentParagraph.Count > 0)
                {
                    paragraphs.Add(string.Join(" ", currentParagraph));
                    currentParagraph.Clear();
                }
            }
            else
            {
                currentParagraph.Add(line.Trim());
            }
        }

        if (currentParagraph.Count > 0)
        {
            paragraphs.Add(string.Join(" ", currentParagraph));
        }

        // If only one paragraph, return as single line
        if (paragraphs.Count == 1)
            return paragraphs[0];

        // Multiple paragraphs - use <para> tags for proper IntelliSense rendering
        var result = new StringBuilder();
        for (int i = 0; i < paragraphs.Count; i++)
        {
            if (i == 0)
            {
                // First paragraph without para tag
                result.Append(paragraphs[i]);
            }
            else
            {
                // Subsequent paragraphs with para tags
                result.Append($"<para>{paragraphs[i]}</para>");
            }
        }

        return result.ToString();
    }

    #region Enum Generation

    /// <summary>
    /// Defines enum groupings for constants. Maps enum name to the list of constant names to include.
    /// </summary>
    private static readonly Dictionary<string, EnumDefinition> EnumDefinitions = new()
    {
        ["Secp256k1EcFlags"] = new EnumDefinition
        {
            Description = "Flags for public key serialization format.",
            IsFlags = false,
            Members = new()
            {
                { "SECP256K1_EC_COMPRESSED", "Compressed format (33 bytes)." },
                { "SECP256K1_EC_UNCOMPRESSED", "Uncompressed format (65 bytes)." },
            }
        },
        ["Secp256k1ContextFlags"] = new EnumDefinition
        {
            Description = "Flags for secp256k1 context creation.",
            IsFlags = false,
            Members = new()
            {
                { "SECP256K1_CONTEXT_NONE", "Creates a context sufficient for all functionality." },
            }
        },
    };

    /// <summary>
    /// Maps function parameters (by function name + param name) to the enum type they should use.
    /// </summary>
    private static readonly Dictionary<(string FunctionName, string ParamName), string> ParameterEnumMappings = new()
    {
        { ("secp256k1_ec_pubkey_serialize", "flags"), "Secp256k1EcFlags" },
    };

    private class EnumDefinition
    {
        public string? Description { get; set; }
        public bool IsFlags { get; set; }
        public Dictionary<string, string?> Members { get; set; } = new();
    }

    /// <summary>
    /// Generates enum types from constants based on predefined groupings.
    /// </summary>
    public void GenerateEnums(StringBuilder sb, Secp256k1Api api)
    {
        foreach (var (enumName, enumDef) in EnumDefinitions)
        {
            sb.AppendLine();
            if (!string.IsNullOrEmpty(enumDef.Description))
            {
                sb.AppendLine($"    /// <summary>{enumDef.Description}</summary>");
            }
            if (enumDef.IsFlags)
            {
                sb.AppendLine("    [Flags]");
            }
            sb.AppendLine($"    public enum {enumName} : uint");
            sb.AppendLine("    {");

            foreach (var (constantName, memberDesc) in enumDef.Members)
            {
                var constant = api.Constants.FirstOrDefault(c => c.Name == constantName);
                if (constant == null) continue;

                // Generate member name by removing SECP256K1_ prefix and converting to PascalCase
                var memberName = GetEnumMemberName(constantName);

                // Use numeric value if available, otherwise try to evaluate the expression
                var value = constant.NumericValue?.ToString() ?? EvaluateConstantValue(constant.Value, api);

                var desc = memberDesc ?? constant.Description;
                if (!string.IsNullOrEmpty(desc))
                {
                    var cleanDesc = CleanDescription(desc);
                    sb.AppendLine($"        /// <summary>{EscapeXml(cleanDesc)}</summary>");
                }
                sb.AppendLine($"        {memberName} = {value},");
            }

            sb.AppendLine("    }");
        }
    }

    /// <summary>
    /// Converts a constant name like SECP256K1_EC_COMPRESSED to a C# enum member name like Compressed.
    /// </summary>
    private static string GetEnumMemberName(string constantName)
    {
        // Remove SECP256K1_ prefix
        var name = constantName;
        if (name.StartsWith("SECP256K1_"))
            name = name.Substring("SECP256K1_".Length);

        // Remove EC_ prefix for EC flags
        if (name.StartsWith("EC_"))
            name = name.Substring("EC_".Length);

        // Remove CONTEXT_ prefix for context flags
        if (name.StartsWith("CONTEXT_"))
            name = name.Substring("CONTEXT_".Length);

        // Convert SCREAMING_SNAKE_CASE to PascalCase
        var parts = name.Split('_');
        return string.Join("", parts.Select(p =>
            p.Length > 0 ? char.ToUpper(p[0]) + p.Substring(1).ToLower() : ""));
    }

    /// <summary>
    /// Evaluates a constant value expression that may reference other constants.
    /// </summary>
    private static string EvaluateConstantValue(string value, Secp256k1Api api)
    {
        // Handle simple numeric values
        if (int.TryParse(value, out var intVal))
            return intVal.ToString();
        if (value.StartsWith("0x") && int.TryParse(value.Substring(2), System.Globalization.NumberStyles.HexNumber, null, out intVal))
            return intVal.ToString();

        // Handle bit shifts like (1 << 8)
        var shiftMatch = System.Text.RegularExpressions.Regex.Match(value, @"\((\d+)\s*<<\s*(\d+)\)");
        if (shiftMatch.Success)
        {
            var baseVal = int.Parse(shiftMatch.Groups[1].Value);
            var shift = int.Parse(shiftMatch.Groups[2].Value);
            return (baseVal << shift).ToString();
        }

        // Handle expressions that reference other constants like (SECP256K1_FLAGS_TYPE_COMPRESSION | SECP256K1_FLAGS_BIT_COMPRESSION)
        var orMatch = System.Text.RegularExpressions.Regex.Match(value, @"\((\w+)\s*\|\s*(\w+)\)");
        if (orMatch.Success)
        {
            var left = ResolveConstantValue(orMatch.Groups[1].Value, api);
            var right = ResolveConstantValue(orMatch.Groups[2].Value, api);
            if (left.HasValue && right.HasValue)
                return (left.Value | right.Value).ToString();
        }

        // Handle single constant reference like (SECP256K1_FLAGS_TYPE_COMPRESSION)
        var singleMatch = System.Text.RegularExpressions.Regex.Match(value, @"\((\w+)\)");
        if (singleMatch.Success)
        {
            var resolved = ResolveConstantValue(singleMatch.Groups[1].Value, api);
            if (resolved.HasValue)
                return resolved.Value.ToString();
        }

        // Fallback - return as-is (will likely cause compile error if invalid)
        return value;
    }

    /// <summary>
    /// Resolves a constant name to its numeric value.
    /// </summary>
    private static long? ResolveConstantValue(string constantName, Secp256k1Api api)
    {
        var constant = api.Constants.FirstOrDefault(c => c.Name == constantName);
        if (constant == null)
            return null;

        if (constant.NumericValue.HasValue)
            return constant.NumericValue.Value;

        // Try to evaluate the expression recursively
        var evaluated = EvaluateConstantValue(constant.Value, api);
        if (long.TryParse(evaluated, out var result))
            return result;

        return null;
    }

    #endregion

    #region Wrapper Generation

    // Functions to skip in wrapper generation (need manual implementation or are internal)
    private static readonly HashSet<string> SkipWrapperFunctions = new()
    {
        "secp256k1_context_create",
        "secp256k1_context_clone",
        "secp256k1_context_destroy",
        "secp256k1_context_set_illegal_callback",
        "secp256k1_context_set_error_callback",
        "secp256k1_context_randomize",
        "secp256k1_context_preallocated_size",
        "secp256k1_context_preallocated_create",
        "secp256k1_context_preallocated_clone_size",
        "secp256k1_context_preallocated_clone",
        "secp256k1_context_preallocated_destroy",
        "secp256k1_ec_pubkey_sort",  // Needs special handling to reorder the C# array based on sorted pointers
    };

    // Functions that return int but NOT as bool (0/1 success/failure)
    // These are comparison functions where the return value is meaningful (0=equal, <0=less, >0=greater)
    private static readonly HashSet<string> IntReturnFunctions = new()
    {
        "secp256k1_ec_pubkey_cmp",
        "secp256k1_xonly_pubkey_cmp",
    };

    // Struct sizes from JSON (secp256k1 opaque types)
    private static readonly Dictionary<string, int> StructSizes = new()
    {
        ["secp256k1_pubkey"] = 64,
        ["secp256k1_ecdsa_signature"] = 64,
        ["secp256k1_ecdsa_recoverable_signature"] = 65,
        ["secp256k1_xonly_pubkey"] = 64,
        ["secp256k1_keypair"] = 96,
        ["secp256k1_musig_keyagg_cache"] = 197,
        ["secp256k1_musig_secnonce"] = 132,
        ["secp256k1_musig_pubnonce"] = 132,
        ["secp256k1_musig_aggnonce"] = 132,
        ["secp256k1_musig_session"] = 133,
        ["secp256k1_musig_partial_sig"] = 36,
    };

    // Map native callback type names to user-friendly C# delegate names
    private static readonly Dictionary<string, string> CallbackDelegateNames = new()
    {
        ["secp256k1_nonce_function"] = "NonceFunction",
        ["secp256k1_ecdh_hash_function"] = "EcdhHashFunction",
        ["secp256k1_nonce_function_hardened"] = "NonceFunctionHardened",
        ["secp256k1_ellswift_xdh_hash_function"] = "EllswiftXdhHashFunction",
    };

    // User-friendly delegates that are already defined in hand-written code (skip generation)
    private static readonly HashSet<string> SkipDelegateGeneration = new()
    {
        // Empty - all delegates are now generated
    };

    public string GenerateWrappers(Secp256k1Api api)
    {
        // Update struct sizes from JSON if available
        var structSizes = new Dictionary<string, int>(StructSizes);
        foreach (var s in api.Structs.Where(s => s.Size > 0))
        {
            structSizes[s.Name] = s.Size;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Secp256k1Net");
        sb.AppendLine("{");

        // Generate enum types from constants
        GenerateEnums(sb, api);

        // Generate user-friendly delegate types for callback functions
        GenerateUserFriendlyCallbackDelegates(sb, api);

        sb.AppendLine("    public unsafe partial class Secp256k1");
        sb.AppendLine("    {");

        foreach (var func in api.Functions.Where(f => !SkipWrapperFunctions.Contains(f.Name) && !f.Deprecated))
        {
            GenerateWrapperMethod(sb, func, structSizes, api);
        }

        // Generate wrappers for global function pointers (like secp256k1_nonce_function_rfc6979)
        foreach (var global in api.GlobalPointers.Where(g => g.Type.StartsWith("secp256k1_") && g.Type.Contains("function")))
        {
            GenerateGlobalFunctionPointerWrapper(sb, global, api, structSizes);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates user-friendly delegate types with Span parameters for callback function types.
    /// </summary>
    private void GenerateUserFriendlyCallbackDelegates(StringBuilder sb, Secp256k1Api api)
    {
        foreach (var fpType in api.FunctionPointerTypes)
        {
            if (!CallbackDelegateNames.TryGetValue(fpType.Name, out var delegateName))
                continue;

            // Skip delegates that are already defined in hand-written code
            if (SkipDelegateGeneration.Contains(delegateName))
                continue;

            sb.AppendLine();
            if (!string.IsNullOrEmpty(fpType.Description))
            {
                sb.AppendLine($"    /// <summary>{FormatXmlDescription(fpType.Description)}</summary>");
            }

            // Generate parameter documentation
            foreach (var param in fpType.Parameters)
            {
                var paramDesc = FormatXmlDescription(param.Description);
                sb.AppendLine($"    /// <param name=\"{SanitizeParamName(param.Name)}\">{paramDesc}</param>");
            }

            if (fpType.ReturnType == "int")
            {
                sb.AppendLine("    /// <returns>1 on success, 0 on failure.</returns>");
            }

            // Generate the delegate with user-friendly Span types
            var returnType = fpType.ReturnType == "int" ? "int" : MapCTypeToCSharp(fpType.ReturnType);
            sb.Append($"    public delegate {returnType} {delegateName}(");

            var paramStrings = new List<string>();
            foreach (var param in fpType.Parameters)
            {
                var paramType = GetUserFriendlyCallbackParamType(param);
                paramStrings.Add($"{paramType} {SanitizeParamName(param.Name)}");
            }

            sb.Append(string.Join(", ", paramStrings));
            sb.AppendLine(");");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Maps a callback parameter type to a user-friendly C# type (Span-based where possible).
    /// </summary>
    private string GetUserFriendlyCallbackParamType(ParameterDef param)
    {
        var cType = param.Type.Trim();
        var direction = param.Direction ?? "in";

        // void* data - keep as IntPtr for user data
        if (cType == "void*" || cType == "const void*")
        {
            return "IntPtr";
        }

        // Pointer types - convert to Span
        if (cType.Contains("*"))
        {
            bool isInput = direction == "in" || cType.StartsWith("const ");
            return isInput ? "ReadOnlySpan<byte>" : "Span<byte>";
        }

        // Primitive types
        return MapCTypeToCSharp(cType);
    }

    private void GenerateWrapperMethod(StringBuilder sb, FunctionDef func, Dictionary<string, int> structSizes, Secp256k1Api api)
    {
        // Check if has function pointer parameter (callback)
        var callbackParams = func.Parameters.Where(p => p.Type.Contains("function") || p.Type.Contains("(*)")).ToList();

        // If any callback is REQUIRED, generate a callback wrapper version
        if (callbackParams.Any(p => p.Nonnull))
        {
            GenerateCallbackWrapperMethod(sb, func, structSizes, callbackParams, api);
            return;
        }

        // Check if this function has array-of-pointers parameters (both "**" and "* const*" patterns)
        var hasArrayOfPointers = func.Parameters.Any(p => p.Type.Contains("**") || p.Type.Contains("* const*"));

        if (hasArrayOfPointers)
        {
            GenerateArrayOfPointersWrapperMethod(sb, func, structSizes);
            return;
        }

        var methodName = GetWrapperMethodName(func.Name);
        var allParameters = GetWrapperParameters(func, structSizes);
        var hasContextParam = func.Parameters.FirstOrDefault()?.Type.Contains("secp256k1_context") == true;

        // Skip context parameter, optional callbacks, and length params for input spans in wrapper signature
        var wrapperParams = (hasContextParam ? allParameters.Skip(1) : allParameters)
            .Where(p => !p.IsOptionalCallback)
            .Where(p => p.LengthForSpanName == null)  // Skip length params - we'll use span.Length
            .ToList();

        // Generate XML documentation
        sb.AppendLine();
        if (!string.IsNullOrEmpty(func.Description))
        {
            sb.AppendLine($"        /// <summary>{FormatXmlDescription(func.Description)}</summary>");
        }

        foreach (var param in wrapperParams)
        {
            if (!string.IsNullOrEmpty(param.Description))
            {
                // XML param names don't use @ prefix
                var xmlParamName = param.WrapperName.TrimStart('@');
                sb.AppendLine($"        /// <param name=\"{xmlParamName}\">{FormatXmlDescription(param.Description)}</param>");
            }
        }

        if (!string.IsNullOrEmpty(func.ReturnDescription))
        {
            sb.AppendLine($"        /// <returns>{FormatXmlDescription(func.ReturnDescription)}</returns>");
        }

        // Determine return type
        // Comparison functions return int (not bool) so the actual comparison result is preserved
        var returnsBool = func.ReturnType == "int" && !IntReturnFunctions.Contains(func.Name);
        var returnType = returnsBool ? "bool" : MapCTypeToCSharp(func.ReturnType);

        // Method signature
        var paramSignature = string.Join(", ", wrapperParams.Select(p => $"{p.WrapperType} {p.WrapperName}"));
        sb.AppendLine($"        public {returnType} {methodName}({paramSignature})");
        sb.AppendLine("        {");

        // Generate validation
        foreach (var param in wrapperParams.Where(p => p.RequiredSize > 0 && p.IsSpan))
        {
            sb.AppendLine($"            if ({param.WrapperName}.Length < {param.RequiredSize})");
            sb.AppendLine($"                throw new ArgumentException($\"{{nameof({param.WrapperName})}} must be at least {param.RequiredSize} bytes\");");
        }

        // Collect span parameters for fixed statement
        var spanParams = wrapperParams.Where(p => p.IsSpan).ToList();
        var refParams = wrapperParams.Where(p => p.IsRefParam).ToList();

        var needsFixed = spanParams.Count > 0 || refParams.Count > 0;

        if (needsFixed)
        {
            sb.AppendLine();

            // Build fixed statement for byte spans
            if (spanParams.Count > 0)
            {
                var fixedDeclarations = spanParams.Select(p =>
                    $"{p.WrapperName}Ptr = &MemoryMarshal.GetReference({p.WrapperName})");
                sb.AppendLine($"            fixed (byte* {string.Join(",\n                ", fixedDeclarations)})");
            }

            // Build fixed statement for ref params
            foreach (var refParam in refParams)
            {
                var cleanName = refParam.WrapperName.TrimStart('@');
                sb.AppendLine($"            fixed ({refParam.RefParamType}* {cleanName}Ptr = &{refParam.WrapperName})");
            }

            sb.AppendLine("            {");

            // Build native call (use allParameters to include optional callbacks as IntPtr.Zero)
            var nativeArgs = BuildNativeCallArgs(func, allParameters, hasContextParam);
            var fieldName = GetFieldName(func.Name);

            if (returnsBool)
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs}) == 1;");
            }
            else if (func.ReturnType == "void")
            {
                sb.AppendLine($"                {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs});");
            }

            sb.AppendLine("            }");
        }
        else
        {
            // No span or ref parameters - direct call (use allParameters to include optional callbacks)
            var nativeArgs = BuildNativeCallArgs(func, allParameters, hasContextParam);
            var fieldName = GetFieldName(func.Name);

            if (returnsBool)
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs}) == 1;");
            }
            else if (func.ReturnType == "void")
            {
                sb.AppendLine($"            {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs});");
            }
        }

        sb.AppendLine("        }");

        // Generate optional callback overload if this function has optional callbacks
        var optionalCallbackParams = callbackParams.Where(p => !p.Nonnull).ToList();
        if (optionalCallbackParams.Count > 0)
        {
            GenerateOptionalCallbackOverload(sb, func, structSizes, optionalCallbackParams, api);
        }
    }

    /// <summary>
    /// Generates an overload that accepts optional callback parameters.
    /// This allows users to provide custom callbacks when needed, while the default overload uses null/default.
    /// </summary>
    private void GenerateOptionalCallbackOverload(StringBuilder sb, FunctionDef func, Dictionary<string, int> structSizes, List<ParameterDef> optionalCallbackParams, Secp256k1Api api)
    {
        var methodName = GetWrapperMethodName(func.Name);
        var hasContextParam = func.Parameters.FirstOrDefault()?.Type.Contains("secp256k1_context") == true;

        // Get the callback type info
        var callbackParam = optionalCallbackParams.FirstOrDefault(p => p.Type.Contains("function"));
        if (callbackParam == null)
            return;

        var nativeCallbackType = callbackParam.Type;

        // Get user-friendly delegate name
        if (!CallbackDelegateNames.TryGetValue(nativeCallbackType, out var userDelegateType))
        {
            // No user-friendly delegate defined, skip
            return;
        }

        // Build wrapper parameters list - include all params including callback and data
        var wrapperParams = new List<(string type, string name, string? desc, ParameterDef original, bool isCallback, bool isData)>();

        foreach (var param in func.Parameters)
        {
            if (param.Type.Contains("secp256k1_context"))
                continue; // Skip context param

            if (param.Type.Contains("function"))
            {
                // Replace native callback type with user-friendly delegate
                wrapperParams.Add((userDelegateType, SanitizeParamName(param.Name), param.Description, param, true, false));
            }
            else if (param.Type == "void*" || param.Type == "const void*")
            {
                // Data pointer accompanying callback
                wrapperParams.Add(("IntPtr", SanitizeParamName(param.Name), param.Description, param, false, true));
            }
            else if (param.Type.Contains("size_t") && param.Type.Contains("*"))
            {
                // Size_t pointer - ref nuint
                wrapperParams.Add(("ref nuint", SanitizeParamName(param.Name), param.Description, param, false, false));
            }
            else if (param.Type.Contains("int") && param.Type.Contains("*") && !param.Type.Contains("uint"))
            {
                // Int pointer - out int
                var dir = param.Direction == "out" ? "out int" : "ref int";
                wrapperParams.Add((dir, SanitizeParamName(param.Name), param.Description, param, false, false));
            }
            else if (param.Type.Contains("*"))
            {
                // Other pointer params become spans
                var isOutput = param.Direction == "out" || !param.Type.StartsWith("const ");
                var spanType = isOutput ? "Span<byte>" : "ReadOnlySpan<byte>";
                wrapperParams.Add((spanType, SanitizeParamName(param.Name), param.Description, param, false, false));
            }
            else
            {
                // Non-pointer params pass through
                wrapperParams.Add((MapCTypeToCSharp(param.Type), SanitizeParamName(param.Name), param.Description, param, false, false));
            }
        }

        // Generate XML documentation
        sb.AppendLine();
        if (!string.IsNullOrEmpty(func.Description))
        {
            sb.AppendLine($"        /// <summary>{FormatXmlDescription(func.Description)}</summary>");
        }

        foreach (var (type, name, desc, _, _, _) in wrapperParams)
        {
            if (!string.IsNullOrEmpty(desc))
            {
                var xmlParamName = name.TrimStart('@');
                sb.AppendLine($"        /// <param name=\"{xmlParamName}\">{FormatXmlDescription(desc)}</param>");
            }
        }

        if (!string.IsNullOrEmpty(func.ReturnDescription))
        {
            sb.AppendLine($"        /// <returns>{FormatXmlDescription(func.ReturnDescription)}</returns>");
        }

        // Method signature
        var returnsBool = func.ReturnType == "int";
        var returnType = returnsBool ? "bool" : MapCTypeToCSharp(func.ReturnType);
        var paramSignature = string.Join(", ", wrapperParams.Select(p => $"{p.type} {p.name}"));
        sb.AppendLine($"        public {returnType} {methodName}({paramSignature})");
        sb.AppendLine("        {");

        // Generate validation for span parameters
        foreach (var (type, name, _, original, _, _) in wrapperParams)
        {
            if (!type.Contains("Span")) continue;

            var size = GetRequiredSize(original, structSizes);
            if (size > 0)
            {
                sb.AppendLine($"            if ({name}.Length < {size})");
                sb.AppendLine($"                throw new ArgumentException($\"{{nameof({name})}} must be at least {size} bytes\");");
            }
        }

        // Find the callback parameter name for marshaling
        var callbackParamInfo = wrapperParams.First(p => p.isCallback);
        var callbackParamName = callbackParamInfo.name;

        sb.AppendLine();

        // Generate the native callback wrapper
        sb.AppendLine($"            {nativeCallbackType} nativeCallback = {GenerateNativeCallbackWrapper(nativeCallbackType, callbackParamName, structSizes, api)};");
        sb.AppendLine();
        sb.AppendLine("            var callbackPtr = Marshal.GetFunctionPointerForDelegate(nativeCallback);");
        sb.AppendLine();

        // Collect span parameters for fixed statement
        var spanParams = wrapperParams.Where(p => p.type.Contains("Span")).ToList();
        var refParams = wrapperParams.Where(p => p.type.StartsWith("ref ") || p.type.StartsWith("out ")).ToList();

        var needsFixed = spanParams.Count > 0 || refParams.Count > 0;

        if (needsFixed)
        {
            // Build fixed statement for byte spans
            if (spanParams.Count > 0)
            {
                var fixedDeclarations = spanParams.Select(p =>
                    $"{p.name}Ptr = &MemoryMarshal.GetReference({p.name})");
                sb.AppendLine($"            fixed (byte* {string.Join(",\n                ", fixedDeclarations)})");
            }

            // Build fixed statement for ref params
            foreach (var refParam in refParams)
            {
                var cleanName = refParam.name.TrimStart('@');
                var refType = refParam.type.Replace("ref ", "").Replace("out ", "");
                sb.AppendLine($"            fixed ({refType}* {cleanName}Ptr = &{refParam.name})");
            }

            sb.AppendLine("            {");

            // Build native call arguments
            var nativeArgs = BuildOptionalCallbackNativeCallArgs(func, wrapperParams, hasContextParam);
            var fieldName = GetFieldName(func.Name);

            if (returnsBool)
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs}) == 1;");
            }
            else if (func.ReturnType == "void")
            {
                sb.AppendLine($"                {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs});");
            }

            sb.AppendLine("            }");
        }
        else
        {
            // No span parameters - direct call
            var nativeArgs = BuildOptionalCallbackNativeCallArgs(func, wrapperParams, hasContextParam);
            var fieldName = GetFieldName(func.Name);

            if (returnsBool)
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs}) == 1;");
            }
            else if (func.ReturnType == "void")
            {
                sb.AppendLine($"            {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs});");
            }
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Builds native call arguments for optional callback overload methods.
    /// </summary>
    private static string BuildOptionalCallbackNativeCallArgs(FunctionDef func, List<(string type, string name, string? desc, ParameterDef original, bool isCallback, bool isData)> wrapperParams, bool hasContextParam)
    {
        var args = new List<string>();

        if (hasContextParam)
        {
            args.Add("_ctx");
        }

        foreach (var (type, name, _, original, isCallback, isData) in wrapperParams)
        {
            if (type.Contains("Span"))
            {
                args.Add($"{name}Ptr");
            }
            else if (isCallback)
            {
                args.Add("callbackPtr");
            }
            else if (isData)
            {
                // Data pointer - pass as void*
                args.Add($"{name}.ToPointer()");
            }
            else if (type.StartsWith("ref ") || type.StartsWith("out "))
            {
                // Use the pinned pointer variable
                var cleanName = name.TrimStart('@');
                args.Add($"{cleanName}Ptr");
            }
            else
            {
                args.Add(name);
            }
        }

        return string.Join(", ", args);
    }

    private List<WrapperParameter> GetWrapperParameters(FunctionDef func, Dictionary<string, int> structSizes)
    {
        var result = new List<WrapperParameter>();

        foreach (var param in func.Parameters)
        {
            var wrapper = new WrapperParameter
            {
                OriginalName = param.Name,
                OriginalType = param.Type,
                Direction = param.Direction ?? "in",
                Description = param.Description,
                IsLengthFor = param.IsLengthFor
            };

            // Determine wrapper type and size
            DetermineWrapperType(wrapper, param, structSizes, func.Name);

            result.Add(wrapper);
        }

        // Second pass: resolve LengthForSpanName for length params where the buffer is a ReadOnlySpan
        foreach (var wrapper in result)
        {
            if (!string.IsNullOrEmpty(wrapper.IsLengthFor))
            {
                // Find the buffer parameter this length is for
                var bufferParam = result.FirstOrDefault(p => p.OriginalName == wrapper.IsLengthFor);
                // Only hide length param if the buffer became a ReadOnlySpan (input buffer)
                if (bufferParam != null && bufferParam.WrapperType == "ReadOnlySpan<byte>")
                {
                    wrapper.LengthForSpanName = bufferParam.WrapperName;
                }
            }
        }

        return result;
    }

    private void DetermineWrapperType(WrapperParameter wrapper, ParameterDef param, Dictionary<string, int> structSizes, string functionName)
    {
        var cType = param.Type.Trim();
        var name = param.Name;
        var direction = param.Direction ?? "in";

        // Context pointer - use IntPtr internally
        if (cType.Contains("secp256k1_context"))
        {
            wrapper.WrapperType = "IntPtr";
            wrapper.WrapperName = "_ctx";
            wrapper.IsContextParam = true;
            return;
        }

        // Function pointer types (callbacks)
        if (cType.Contains("function") || cType.Contains("(*)"))
        {
            wrapper.WrapperType = "IntPtr";
            wrapper.WrapperName = SanitizeParamName(name);
            // If nonnull is false, this is an optional callback - will pass IntPtr.Zero
            wrapper.IsOptionalCallback = !param.Nonnull;
            return;
        }

        // void* data parameter that typically accompanies callback - mark as optional too
        // These are usually named "data" or "ndata" and follow a callback parameter
        if (cType == "void*" || cType == "const void*")
        {
            wrapper.WrapperType = "IntPtr";
            wrapper.WrapperName = SanitizeParamName(name);
            // Mark as optional if nonnull is false
            wrapper.IsOptionalCallback = !param.Nonnull;
            return;
        }

        // Size_t pointer (output length) - treat as ref parameter that needs fixed
        if (cType.Contains("size_t") && cType.Contains("*"))
        {
            wrapper.WrapperType = "ref nuint";
            wrapper.WrapperName = SanitizeParamName(name);
            wrapper.IsRefParam = true;
            wrapper.RefParamType = "nuint";
            return;
        }

        // Int pointer (e.g., recid) - treat as ref/out parameter that needs fixed
        if (cType.Contains("int") && cType.Contains("*") && !cType.Contains("uint"))
        {
            wrapper.WrapperType = direction == "out" ? "out int" : "ref int";
            wrapper.WrapperName = SanitizeParamName(name);
            wrapper.IsRefParam = true;
            wrapper.RefParamType = "int";
            return;
        }

        // Check for enum mappings for this parameter
        if (ParameterEnumMappings.TryGetValue((functionName, name), out var enumType))
        {
            wrapper.WrapperType = enumType;
            wrapper.WrapperName = SanitizeParamName(name);
            wrapper.IsEnumParam = true;
            return;
        }

        // Non-pointer primitive types
        if (!cType.Contains("*"))
        {
            wrapper.WrapperType = MapCTypeToCSharp(cType);
            wrapper.WrapperName = SanitizeParamName(name);
            return;
        }

        // Pointer types - determine if they should be Span<byte> or ReadOnlySpan<byte>
        wrapper.IsSpan = true;

        // Determine span type based on direction and const
        bool isInput = direction == "in" || cType.StartsWith("const ");
        wrapper.WrapperType = isInput ? "ReadOnlySpan<byte>" : "Span<byte>";
        wrapper.WrapperName = GetWrapperParamName(name);

        // Determine required size - prefer pre-computed value from JSON
        wrapper.RequiredSize = GetRequiredSize(param, structSizes);
    }

    /// <summary>
    /// Gets the required size for a parameter, using pre-computed Size from the JSON if available,
    /// or falling back to struct size lookup.
    /// </summary>
    private int GetRequiredSize(ParameterDef param, Dictionary<string, int> structSizes)
    {
        // Use pre-computed size from JSON if available (set by header parser)
        if (param.Size.HasValue)
        {
            return param.Size.Value;
        }

        // Fallback: check if it's a known struct type
        foreach (var kvp in structSizes)
        {
            if (param.Type.Contains(kvp.Key))
            {
                return kvp.Value;
            }
        }

        // Default - no size validation
        return 0;
    }

    private string GetWrapperMethodName(string functionName)
    {
        // secp256k1_ec_pubkey_create -> EcPubkeyCreate
        var name = functionName;

        // Remove secp256k1_ prefix
        if (name.StartsWith("secp256k1_"))
        {
            name = name.Substring("secp256k1_".Length);
        }

        // Convert snake_case to PascalCase
        var parts = name.Split('_');
        var result = string.Join("", parts.Select(p =>
            p.Length > 0 ? char.ToUpper(p[0]) + p.Substring(1).ToLower() : ""));

        // Handle common acronyms
        result = result.Replace("Ecdsa", "Ecdsa")
                       .Replace("Ecdh", "Ecdh")
                       .Replace("Ec", "Ec");

        return result;
    }

    private string GetWrapperParamName(string originalName)
    {
        // Convert C-style names to C# style
        var name = originalName;

        // Remove common suffixes for cleaner names
        if (name.EndsWith("32") || name.EndsWith("33") || name.EndsWith("64") || name.EndsWith("65"))
        {
            // Keep the suffix in the name for clarity
        }

        return SanitizeParamName(name);
    }

    private static string BuildNativeCallArgs(FunctionDef func, List<WrapperParameter> allParams, bool hasContextParam)
    {
        var args = new List<string>();

        if (hasContextParam)
        {
            args.Add("_ctx");
        }

        foreach (var param in allParams.Where(p => !p.IsContextParam))
        {
            if (param.IsOptionalCallback)
            {
                // Optional callback and data parameters - pass IntPtr.Zero
                // For void* data parameters, need to use IntPtr.Zero.ToPointer()
                if (param.OriginalType == "void*" || param.OriginalType == "const void*")
                {
                    args.Add("IntPtr.Zero.ToPointer()");
                }
                else
                {
                    args.Add("IntPtr.Zero");
                }
            }
            else if (param.LengthForSpanName != null)
            {
                // This is a length param for an input span - use span.Length
                args.Add($"(nuint){param.LengthForSpanName}.Length");
            }
            else if (param.IsSpan)
            {
                args.Add($"{param.WrapperName}Ptr");
            }
            else if (param.IsRefParam)
            {
                // Use the pinned pointer variable
                var cleanName = param.WrapperName.TrimStart('@');
                args.Add($"{cleanName}Ptr");
            }
            else if (param.IsEnumParam)
            {
                // Cast enum to uint for native call
                args.Add($"(uint){param.WrapperName}");
            }
            else
            {
                args.Add(param.WrapperName);
            }
        }

        return string.Join(", ", args);
    }

    private class WrapperParameter
    {
        public string OriginalName { get; set; } = "";
        public string OriginalType { get; set; } = "";
        public string WrapperType { get; set; } = "";
        public string WrapperName { get; set; } = "";
        public string Direction { get; set; } = "in";
        public string? Description { get; set; }
        public int RequiredSize { get; set; }
        public bool IsSpan { get; set; }
        public bool IsContextParam { get; set; }
        public bool IsRefParam { get; set; }
        public string RefParamType { get; set; } = "";
        public bool IsArrayOfPointers { get; set; }
        public int ElementSize { get; set; }
        public string? CountParamName { get; set; }
        public bool IsOptionalCallback { get; set; }  // Optional callback/data parameter - pass IntPtr.Zero
        public string? IsLengthFor { get; set; }  // If this is a length param, the name of the buffer param it's for
        public string? LengthForSpanName { get; set; }  // The wrapper name of the span this length is for (resolved)
        public bool IsEnumParam { get; set; }  // If true, this param uses an enum type and needs casting to uint
    }

    /// <summary>
    /// Generates wrapper methods for functions with array-of-pointers parameters.
    /// These functions take a pointer to an array of pointers (e.g., secp256k1_pubkey * const*).
    /// The generated wrapper accepts a ReadOnlySpan of ReadOnlySpan elements.
    /// </summary>
    private void GenerateArrayOfPointersWrapperMethod(StringBuilder sb, FunctionDef func, Dictionary<string, int> structSizes)
    {
        var methodName = GetWrapperMethodName(func.Name);
        var hasContextParam = func.Parameters.FirstOrDefault()?.Type.Contains("secp256k1_context") == true;

        // Find the array-of-pointers parameter and its count parameter
        var arrayParam = func.Parameters.FirstOrDefault(p => p.Type.Contains("**") || p.Type.Contains("* const*"));
        if (arrayParam == null) return;

        // Find the count parameter (usually named n, n_pubkeys, n_pubnonces, n_sigs)
        var countParam = func.Parameters.FirstOrDefault(p =>
            p.Name == "n" ||
            p.Name.StartsWith("n_") ||
            p.Name.EndsWith("_count"));

        // Determine element size from type
        var elementSize = GetElementSizeFromType(arrayParam.Type, structSizes);

        // Build wrapper parameters
        var wrapperParams = new List<(string type, string name, string? desc, ParameterDef original)>();

        foreach (var param in func.Parameters)
        {
            if (param.Type.Contains("secp256k1_context"))
                continue; // Skip context param

            if (param == countParam)
                continue; // Skip count param - we'll infer it from the array length

            if (param == arrayParam)
            {
                // Array of byte arrays parameter (can't use Span[] since Span is a ref struct)
                wrapperParams.Add(("byte[][]", SanitizeParamName(param.Name), param.Description, param));
            }
            else if (param.Type.Contains('*'))
            {
                // Other pointer params become spans
                var isOutput = param.Direction == "out" || !param.Type.StartsWith("const ");
                var spanType = isOutput ? "Span<byte>" : "ReadOnlySpan<byte>";
                wrapperParams.Add((spanType, SanitizeParamName(param.Name), param.Description, param));
            }
            else
            {
                // Non-pointer params pass through
                wrapperParams.Add((MapCTypeToCSharp(param.Type), SanitizeParamName(param.Name), param.Description, param));
            }
        }

        // Generate XML documentation
        sb.AppendLine();
        if (!string.IsNullOrEmpty(func.Description))
        {
            sb.AppendLine($"        /// <summary>{FormatXmlDescription(func.Description)}</summary>");
        }

        foreach (var (type, name, desc, _) in wrapperParams)
        {
            if (!string.IsNullOrEmpty(desc))
            {
                // XML param names don't use @ prefix for escaped keywords
                var xmlParamName = name.TrimStart('@');
                sb.AppendLine($"        /// <param name=\"{xmlParamName}\">{FormatXmlDescription(desc)}</param>");
            }
        }

        if (!string.IsNullOrEmpty(func.ReturnDescription))
        {
            sb.AppendLine($"        /// <returns>{FormatXmlDescription(func.ReturnDescription)}</returns>");
        }

        // Method signature
        var returnsBool = func.ReturnType == "int";
        var returnType = returnsBool ? "bool" : MapCTypeToCSharp(func.ReturnType);
        var paramSignature = string.Join(", ", wrapperParams.Select(p => $"{p.type} {p.name}"));
        sb.AppendLine($"        public {returnType} {methodName}({paramSignature})");
        sb.AppendLine("        {");

        // Get the array parameter name
        var arrayParamName = SanitizeParamName(arrayParam.Name);

        // Generate validation for array
        sb.AppendLine($"            if ({arrayParamName} == null || {arrayParamName}.Length == 0)");
        sb.AppendLine($"                throw new ArgumentException($\"{{nameof({arrayParamName})}} must not be null or empty\");");

        // Generate validation for element sizes
        if (elementSize > 0)
        {
            sb.AppendLine($"            for (int i = 0; i < {arrayParamName}.Length; i++)");
            sb.AppendLine("            {");
            sb.AppendLine($"                if ({arrayParamName}[i] == null || {arrayParamName}[i].Length < {elementSize})");
            sb.AppendLine($"                    throw new ArgumentException($\"{{nameof({arrayParamName})}}[{{i}}] must be at least {elementSize} bytes\");");
            sb.AppendLine("            }");
        }

        // Generate validation for other span parameters
        foreach (var (type, name, _, original) in wrapperParams)
        {
            if (original == arrayParam) continue;
            if (!type.Contains("Span")) continue;

            var size = GetRequiredSize(original, structSizes);
            if (size > 0)
            {
                sb.AppendLine($"            if ({name}.Length < {size})");
                sb.AppendLine($"                throw new ArgumentException($\"{{nameof({name})}} must be at least {size} bytes\");");
            }
        }

        sb.AppendLine();

        // Allocate native pointer array
        sb.AppendLine($"            var count = {arrayParamName}.Length;");
        sb.AppendLine("            var ptrSize = IntPtr.Size;");
        sb.AppendLine("            var nativePtrArray = Marshal.AllocHGlobal(ptrSize * count);");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // Collect all span parameters (excluding the array-of-pointers)
        var otherSpanParams = wrapperParams
            .Where(p => p.original != arrayParam && p.type.Contains("Span"))
            .ToList();

        // Build fixed statements
        var indent = "                ";
        if (otherSpanParams.Count > 0)
        {
            var fixedDeclarations = otherSpanParams.Select(p =>
                $"{p.name}Ptr = &MemoryMarshal.GetReference({p.name})");
            sb.AppendLine($"{indent}fixed (byte* {string.Join(",\n                    ", fixedDeclarations)})");
            indent = "                    ";
        }

        // Generate pinning code using Span's Pin() method or stackalloc for GCHandles
        sb.AppendLine($"{indent}{{");

        // Use GCHandle to pin the array elements
        sb.AppendLine($"{indent}    var handles = new GCHandle[count];");
        sb.AppendLine($"{indent}    try");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        for (int i = 0; i < count; i++)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            handles[i] = GCHandle.Alloc({arrayParamName}[i], GCHandleType.Pinned);");
        sb.AppendLine($"{indent}            Marshal.WriteIntPtr(nativePtrArray, i * ptrSize, handles[i].AddrOfPinnedObject());");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();

        // Build native call arguments
        var nativeArgs = new List<string>();
        if (hasContextParam)
            nativeArgs.Add("_ctx");

        foreach (var param in func.Parameters)
        {
            if (param.Type.Contains("secp256k1_context"))
                continue;

            if (param == arrayParam)
            {
                nativeArgs.Add("nativePtrArray");
            }
            else if (param == countParam)
            {
                nativeArgs.Add("(nuint)count");
            }
            else if (param.Type.Contains('*'))
            {
                nativeArgs.Add($"{SanitizeParamName(param.Name)}Ptr");
            }
            else
            {
                nativeArgs.Add(SanitizeParamName(param.Name));
            }
        }

        var fieldName = GetFieldName(func.Name);
        var argsStr = string.Join(", ", nativeArgs);

        if (returnsBool)
        {
            sb.AppendLine($"{indent}        return {fieldName}({argsStr}) == 1;");
        }
        else if (func.ReturnType == "void")
        {
            sb.AppendLine($"{indent}        {fieldName}({argsStr});");
        }
        else
        {
            sb.AppendLine($"{indent}        return {fieldName}({argsStr});");
        }

        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}    finally");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        for (int i = 0; i < count; i++)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            if (handles[i].IsAllocated)");
        sb.AppendLine($"{indent}                handles[i].Free();");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");

        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                Marshal.FreeHGlobal(nativePtrArray);");
        sb.AppendLine("            }");

        sb.AppendLine("        }");
    }

    private static int GetElementSizeFromType(string type, Dictionary<string, int> structSizes)
    {
        // Extract the struct type from "const secp256k1_pubkey * const*"
        foreach (var kvp in structSizes)
        {
            if (type.Contains(kvp.Key))
            {
                return kvp.Value;
            }
        }
        return 0;
    }

    /// <summary>
    /// Generates wrapper methods for functions with required callback parameters.
    /// These methods accept user-friendly delegates and marshal them to native function pointers.
    /// </summary>
    private void GenerateCallbackWrapperMethod(StringBuilder sb, FunctionDef func, Dictionary<string, int> structSizes, List<ParameterDef> callbackParams, Secp256k1Api api)
    {
        var methodName = GetWrapperMethodName(func.Name);
        var hasContextParam = func.Parameters.FirstOrDefault()?.Type.Contains("secp256k1_context") == true;

        // Get the callback type info
        var callbackParam = callbackParams.First(p => p.Type.Contains("function"));
        var nativeCallbackType = callbackParam.Type;

        // Get user-friendly delegate name
        if (!CallbackDelegateNames.TryGetValue(nativeCallbackType, out var userDelegateType))
        {
            // No user-friendly delegate defined, skip
            return;
        }

        // Build wrapper parameters list
        var wrapperParams = new List<(string type, string name, string? desc, ParameterDef original)>();

        foreach (var param in func.Parameters)
        {
            if (param.Type.Contains("secp256k1_context"))
                continue; // Skip context param

            if (param.Type.Contains("function"))
            {
                // Replace native callback type with user-friendly delegate
                wrapperParams.Add((userDelegateType, SanitizeParamName(param.Name), param.Description, param));
            }
            else if (param.Type == "void*" || param.Type == "const void*")
            {
                // Data pointer accompanying callback
                wrapperParams.Add(("IntPtr", SanitizeParamName(param.Name), param.Description, param));
            }
            else if (param.Type.Contains("*"))
            {
                // Other pointer params become spans
                var isOutput = param.Direction == "out" || !param.Type.StartsWith("const ");
                var spanType = isOutput ? "Span<byte>" : "ReadOnlySpan<byte>";
                wrapperParams.Add((spanType, SanitizeParamName(param.Name), param.Description, param));
            }
            else
            {
                // Non-pointer params pass through
                wrapperParams.Add((MapCTypeToCSharp(param.Type), SanitizeParamName(param.Name), param.Description, param));
            }
        }

        // Generate XML documentation
        sb.AppendLine();
        if (!string.IsNullOrEmpty(func.Description))
        {
            sb.AppendLine($"        /// <summary>{FormatXmlDescription(func.Description)}</summary>");
        }

        foreach (var (type, name, desc, _) in wrapperParams)
        {
            if (!string.IsNullOrEmpty(desc))
            {
                var xmlParamName = name.TrimStart('@');
                sb.AppendLine($"        /// <param name=\"{xmlParamName}\">{FormatXmlDescription(desc)}</param>");
            }
        }

        if (!string.IsNullOrEmpty(func.ReturnDescription))
        {
            sb.AppendLine($"        /// <returns>{FormatXmlDescription(func.ReturnDescription)}</returns>");
        }

        // Method signature
        var returnsBool = func.ReturnType == "int";
        var returnType = returnsBool ? "bool" : MapCTypeToCSharp(func.ReturnType);
        var paramSignature = string.Join(", ", wrapperParams.Select(p => $"{p.type} {p.name}"));
        sb.AppendLine($"        public {returnType} {methodName}({paramSignature})");
        sb.AppendLine("        {");

        // Generate validation for span parameters
        foreach (var (type, name, _, original) in wrapperParams)
        {
            if (!type.Contains("Span")) continue;

            var size = GetRequiredSize(original, structSizes);
            if (size > 0)
            {
                sb.AppendLine($"            if ({name}.Length < {size})");
                sb.AppendLine($"                throw new ArgumentException($\"{{nameof({name})}} must be at least {size} bytes\");");
            }
        }

        // Find the callback parameter name for marshaling
        var callbackParamInfo = wrapperParams.First(p => p.type == userDelegateType);
        var callbackParamName = callbackParamInfo.name;

        sb.AppendLine();

        // Generate the native callback wrapper
        // We need to look up the function pointer type definition to generate the wrapper
        sb.AppendLine($"            {nativeCallbackType} nativeCallback = {GenerateNativeCallbackWrapper(nativeCallbackType, callbackParamName, structSizes, api)};");
        sb.AppendLine();
        sb.AppendLine("            var callbackPtr = Marshal.GetFunctionPointerForDelegate(nativeCallback);");
        sb.AppendLine();

        // Collect span parameters for fixed statement
        var spanParams = wrapperParams.Where(p => p.type.Contains("Span")).ToList();

        if (spanParams.Count > 0)
        {
            var fixedDeclarations = spanParams.Select(p =>
                $"{p.name}Ptr = &MemoryMarshal.GetReference({p.name})");
            sb.AppendLine($"            fixed (byte* {string.Join(",\n                ", fixedDeclarations)})");
            sb.AppendLine("            {");

            // Build native call arguments
            var nativeArgs = BuildCallbackNativeCallArgs(func, wrapperParams, hasContextParam);
            var fieldName = GetFieldName(func.Name);

            if (returnsBool)
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs}) == 1;");
            }
            else if (func.ReturnType == "void")
            {
                sb.AppendLine($"                {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs});");
            }

            sb.AppendLine("            }");
        }
        else
        {
            // No span parameters - direct call
            var nativeArgs = BuildCallbackNativeCallArgs(func, wrapperParams, hasContextParam);
            var fieldName = GetFieldName(func.Name);

            if (returnsBool)
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs}) == 1;");
            }
            else if (func.ReturnType == "void")
            {
                sb.AppendLine($"            {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs});");
            }
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Generates the native callback wrapper lambda that converts pointers to Spans and calls the user delegate.
    /// </summary>
    private string GenerateNativeCallbackWrapper(string nativeCallbackType, string userCallbackParamName, Dictionary<string, int> structSizes, Secp256k1Api api)
    {
        // Look up the function pointer type definition
        var fpType = api.FunctionPointerTypes.FirstOrDefault(f => f.Name == nativeCallbackType);
        if (fpType == null)
        {
            throw new NotSupportedException($"Unknown callback type: {nativeCallbackType}");
        }

        // Build the lambda parameter list (native types)
        var lambdaParams = new List<string>();
        foreach (var param in fpType.Parameters)
        {
            var nativeType = MapCTypeToCSharpForFunctionPointer(param.Type, param.Name);
            lambdaParams.Add($"{nativeType} {param.Name}");
        }

        // Build the span conversion statements and delegate call arguments
        var spanConversions = new List<string>();
        var delegateArgs = new List<string>();

        // Build a map of length parameters for variable-length buffers
        var lengthParams = new Dictionary<string, string>(); // buffer name -> length param name
        for (int i = 0; i < fpType.Parameters.Count; i++)
        {
            var param = fpType.Parameters[i];
            if (param.Type.Contains("size_t") && !param.Type.Contains("*"))
            {
                // This is a length parameter - find the preceding buffer it belongs to
                // Convention: length param follows buffer param (e.g., msg, msglen)
                if (i > 0)
                {
                    var prevParam = fpType.Parameters[i - 1];
                    if (prevParam.Type.Contains("*") && param.Name.StartsWith(prevParam.Name.TrimEnd('*')))
                    {
                        lengthParams[prevParam.Name] = param.Name;
                    }
                }
            }
        }

        foreach (var param in fpType.Parameters)
        {
            if (param.Type == "void*" && (param.Name == "data" || param.Name == "d"))
            {
                // Data pointer - convert to IntPtr
                delegateArgs.Add($"(IntPtr){param.Name}");
            }
            else if (param.Type.Contains("*") && (param.Type.Contains("char") || param.Type.Contains("void")))
            {
                // Pointer parameter - convert to Span
                var isOutput = param.Direction == "out" || !param.Type.StartsWith("const ");
                var spanType = isOutput ? "Span<byte>" : "ReadOnlySpan<byte>";
                var spanVarName = $"{param.Name}Span";

                // Determine the size
                // Check for variable-length buffer with associated length param (from JSON LengthParam)
                if (!string.IsNullOrEmpty(param.LengthParam))
                {
                    // Variable-length buffer - check for null and use length param
                    var nullCheck = param.Nonnull ? "" : $"{param.Name} != null ? ";
                    var nullFallback = param.Nonnull ? "" : $" : {spanType}.Empty";
                    spanConversions.Add($"var {spanVarName} = {nullCheck}new {spanType}({param.Name}, (int){param.LengthParam}){nullFallback};");
                    delegateArgs.Add(spanVarName);
                }
                else if (lengthParams.TryGetValue(param.Name, out var lenParam))
                {
                    // Fallback: Variable-length buffer detected by naming convention
                    var nullCheck = param.Nonnull ? "" : $"{param.Name} != null ? ";
                    var nullFallback = param.Nonnull ? "" : $" : {spanType}.Empty";
                    spanConversions.Add($"var {spanVarName} = {nullCheck}new {spanType}({param.Name}, (int){lenParam}){nullFallback};");
                    delegateArgs.Add(spanVarName);
                }
                else
                {
                    // Fixed-size buffer - use pre-computed Size from JSON, or fallback to struct lookup
                    var size = GetRequiredSize(param, structSizes);
                    if (size == 0)
                    {
                        // Default to 32 for unknown sizes (common case)
                        size = 32;
                    }

                    if (!param.Nonnull && param.Direction != "out")
                    {
                        // Nullable input - check for null
                        spanConversions.Add($"var {spanVarName} = {param.Name} != null ? new {spanType}({param.Name}, {size}) : {spanType}.Empty;");
                    }
                    else
                    {
                        spanConversions.Add($"var {spanVarName} = new {spanType}({param.Name}, {size});");
                    }
                    delegateArgs.Add(spanVarName);
                }
            }
            else if (param.Type.Contains("size_t") && !param.Type.Contains("*"))
            {
                // Length parameter - pass through to delegate (some delegates want the length too)
                delegateArgs.Add(param.Name);
            }
            else
            {
                // Other parameters - pass through directly
                delegateArgs.Add(param.Name);
            }
        }

        // Build the lambda body
        var sb = new StringBuilder();
        sb.Append($"({string.Join(", ", lambdaParams)}) =>\n            {{\n");
        foreach (var conversion in spanConversions)
        {
            sb.Append($"                {conversion}\n");
        }
        sb.Append($"                return {userCallbackParamName}({string.Join(", ", delegateArgs)});\n");
        sb.Append("            }");

        return sb.ToString();
    }

    /// <summary>
    /// Builds native call arguments for callback wrapper methods.
    /// </summary>
    private static string BuildCallbackNativeCallArgs(FunctionDef func, List<(string type, string name, string? desc, ParameterDef original)> wrapperParams, bool hasContextParam)
    {
        var args = new List<string>();

        if (hasContextParam)
        {
            args.Add("_ctx");
        }

        foreach (var (type, name, _, original) in wrapperParams)
        {
            if (type.Contains("Span"))
            {
                args.Add($"{name}Ptr");
            }
            else if (original.Type.Contains("function"))
            {
                args.Add("callbackPtr");
            }
            else if (type == "IntPtr" && (original.Type == "void*" || original.Type == "const void*"))
            {
                // Data pointer - pass as void*
                args.Add($"{name}.ToPointer()");
            }
            else
            {
                args.Add(name);
            }
        }

        return string.Join(", ", args);
    }

    /// <summary>
    /// Generates wrapper methods for global function pointers like secp256k1_nonce_function_rfc6979.
    /// These are static function pointers exported from the native library that can be invoked directly.
    /// </summary>
    private void GenerateGlobalFunctionPointerWrapper(StringBuilder sb, GlobalPointer global, Secp256k1Api api, Dictionary<string, int> structSizes)
    {
        // Find the function pointer type definition
        var fpType = api.FunctionPointerTypes.FirstOrDefault(f => f.Name == global.Type);
        if (fpType == null)
            return;

        // Generate method name from global name (e.g., secp256k1_nonce_function_rfc6979 -> NonceFunctionRfc6979)
        var methodName = GetWrapperMethodName(global.Name);
        var fieldName = GetFieldName(global.Name);

        // Build wrapper parameters list
        var wrapperParams = new List<(string type, string name, string? desc, ParameterDef original)>();

        foreach (var param in fpType.Parameters)
        {
            var isOutput = param.Direction == "out" || !param.Type.StartsWith("const ");

            if (param.Type == "void*" || param.Type == "const void*")
            {
                // Data pointer - convert to Span<byte> for user convenience
                var spanType = param.Type.StartsWith("const ") ? "ReadOnlySpan<byte>" : "Span<byte>";
                wrapperParams.Add((spanType, SanitizeParamName(param.Name), param.Description, param));
            }
            else if (param.Type.Contains("*"))
            {
                // Pointer params become spans
                var spanType = isOutput ? "Span<byte>" : "ReadOnlySpan<byte>";
                wrapperParams.Add((spanType, SanitizeParamName(param.Name), param.Description, param));
            }
            else
            {
                // Non-pointer params pass through
                wrapperParams.Add((MapCTypeToCSharp(param.Type), SanitizeParamName(param.Name), param.Description, param));
            }
        }

        // Generate XML documentation
        sb.AppendLine();
        if (!string.IsNullOrEmpty(global.Description))
        {
            sb.AppendLine($"        /// <summary>{FormatXmlDescription(global.Description)}</summary>");
        }

        foreach (var (type, name, desc, _) in wrapperParams)
        {
            if (!string.IsNullOrEmpty(desc))
            {
                var xmlParamName = name.TrimStart('@');
                sb.AppendLine($"        /// <param name=\"{xmlParamName}\">{FormatXmlDescription(desc)}</param>");
            }
        }

        if (fpType.ReturnType == "int")
        {
            sb.AppendLine("        /// <returns>True on success, false on failure.</returns>");
        }

        // Method signature
        var returnsBool = fpType.ReturnType == "int";
        var returnType = returnsBool ? "bool" : MapCTypeToCSharp(fpType.ReturnType);
        var paramSignature = string.Join(", ", wrapperParams.Select(p => $"{p.type} {p.name}"));
        sb.AppendLine($"        public {returnType} {methodName}({paramSignature})");
        sb.AppendLine("        {");

        // Generate validation for span parameters
        // Only validate parameters that are required (nonnull) or likely required based on their name
        // Skip validation for params like "algo16" which are documented as nullable
        foreach (var (type, name, _, original) in wrapperParams)
        {
            if (!type.Contains("Span")) continue;

            var size = GetRequiredSize(original, structSizes);
            if (size > 0)
            {
                // Skip validation for parameters marked as optional in the JSON
                // (e.g., algo16 is documented as "will be NULL for ECDSA for compatibility")
                if (original.IsOptional) continue;

                sb.AppendLine($"            if ({name}.Length < {size})");
                sb.AppendLine($"                throw new ArgumentException($\"{{nameof({name})}} must be at least {size} bytes\");");
            }
        }

        // Collect span parameters for fixed statement
        var spanParams = wrapperParams.Where(p => p.type.Contains("Span")).ToList();

        if (spanParams.Count > 0)
        {
            var fixedDeclarations = spanParams.Select(p =>
                $"{p.name}Ptr = &MemoryMarshal.GetReference({p.name})");
            sb.AppendLine($"            fixed (byte* {string.Join(",\n                ", fixedDeclarations)})");
            sb.AppendLine("            {");

            // Build native call arguments
            var nativeArgs = BuildGlobalFunctionPointerCallArgs(wrapperParams);

            if (returnsBool)
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs}) == 1;");
            }
            else if (fpType.ReturnType == "void")
            {
                sb.AppendLine($"                {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"                return {fieldName}({nativeArgs});");
            }

            sb.AppendLine("            }");
        }
        else
        {
            // No span parameters - direct call
            var nativeArgs = BuildGlobalFunctionPointerCallArgs(wrapperParams);

            if (returnsBool)
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs}) == 1;");
            }
            else if (fpType.ReturnType == "void")
            {
                sb.AppendLine($"            {fieldName}({nativeArgs});");
            }
            else
            {
                sb.AppendLine($"            return {fieldName}({nativeArgs});");
            }
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Builds native call arguments for global function pointer wrapper methods.
    /// </summary>
    private static string BuildGlobalFunctionPointerCallArgs(List<(string type, string name, string? desc, ParameterDef original)> wrapperParams)
    {
        var args = new List<string>();

        foreach (var (type, name, _, original) in wrapperParams)
        {
            if (type.Contains("Span"))
            {
                args.Add($"{name}Ptr");
            }
            else
            {
                args.Add(name);
            }
        }

        return string.Join(", ", args);
    }

    #endregion
}
